import type { Lang } from "../i18n";
const en = {
  mangaModels: "Manga models",
  modelDownloadHint:
    "Weights are downloaded from Hugging Face only when requested and cached locally. Closing this dialog keeps the download running. After an app restart, resume it here.",
  modelExperimental:
    "Experimental cleanup model. Downloading does not enable manga processing: runtime compatibility and image quality still need validation.",
  modelMissing: "Not downloaded",
  modelDownloading: "Downloading",
  modelVerifying: "Verifying file",
  modelPaused: "Download paused",
  modelDownloaded: "Downloaded and verified",
  modelDownload: "Download from Hugging Face",
  modelPause: "Pause download",
  modelRemove: "Remove local files",
  modelUnknown: "This model is not in the catalog.",
  modelBusy: "Another download is in progress.",
  modelNetwork: "Download interrupted. Check your connection and resume.",
  modelSizeError:
    "The server returned an unexpected file size or range. Download was not installed.",
  modelHashError: "File verification failed. Download it again.",
  modelStorageError:
    "Cannot access the model cache. Check free disk space and file permissions.",

  unsupported:
    "This project uses an unsupported format. Create a new project from its source.",
  commands: "Commands",
  library: "Projects",
  newProject: "New project",
  importArchive: "Import project",
  settings: "Settings",
  book: "Book",
  manga: "Manga",
  close: "Close",
  cancel: "Cancel",
  save: "Save",
  retry: "Retry",
  reload: "Discard local edits and reload",
  delete: "Delete project",
  deleteConfirm:
    "Delete this project and its results? Source files will be kept.",
  welcome: "A workspace for every translation",
  welcomeHint:
    "Create a book or manga project. Choose its languages once, then work with the original and translation side by side.",
  emptyProjects: "No projects yet",
  open: "Open",
  loading: "Loading…",
  error: "The operation could not be completed.",
  noKey: "Add an API key in Settings to start processing.",
  conflict:
    "This content changed elsewhere. Your local edits are kept. Reload to use the saved version.",
  exists: "A file with this name already exists. Choose another name.",
  incomplete:
    "Some chapters need translation or review. Complete them, or choose originals for unfinished chapters.",
  chooseKind: "What are you translating?",
  chooseSource: "Choose source",
  sourceFile: "Source file",
  name: "Project name",
  sourceLanguage: "Original language",
  targetLanguage: "Translation language",
  fixedLanguages: "These languages are fixed for this project.",
  create: "Create project",
  metadataAfterCreate:
    "Generate title and summary after creation (uses your AI provider)",
  choose: "Choose…",
  preview: "Import preview",
  bookFormats: "TXT, EPUB, FB2, PDF or ZIP",
  mangaFormats: "CBZ or ZIP with page images",
  importWarning: "Check the source preview before creating the project.",
  chapters: "Chapters",
  chapterFilter: "Find a chapter",
  reader: "Text",
  overview: "Overview",
  glossary: "Glossary",
  reference: "Reference",
  replace: "Find and replace",
  export: "Export",
  jobs: "Jobs",
  noJobs: "No processing jobs",
  translateChapter: "Translate chapter",
  translateBatch: "Translate batch",
  bookTitle: "Book title",
  cover: "Cover",
  chooseCover: "Choose cover",
  removeCover: "Remove cover",
  useGenerated: "Use generated value",
  bookPrompt: "Book translation instructions",
  bookPromptHint:
    "Applied to the next batch. Earlier translations remain available for review. Stop an active batch before changing its instructions.",

  batchCount: "Chapters per batch",
  noEligibleChapters: "No untranslated text chapters in this selection.",
  batchHint:
    "Stops after this batch. Review translations and glossary before starting the next one.",
  force: "Replace existing translations",
  instructions: "Chapter instructions",
  original: "Original",
  translation: "Translation",
  noTranslation: "Translate this chapter to start editing.",
  noChapter: "Choose a chapter",
  saving: "Saving…",
  saved: "Saved",
  unsaved: "Unsaved changes",
  review: "Needs review",
  current: "Current",
  metadata: "Book details",
  generateMetadata: "Generate details",
  noMetadata: "No generated details yet.",
  staleMetadata: "Details were generated from an earlier version.",
  source: "Source",
  author: "Author",
  summary: "Summary",
  extractTerms: "Extract terms",
  newTerm: "Add term",
  termSource: "Original term",
  termTarget: "Translation",
  termKind: "Type",
  pinned: "Pinned",
  occurrences: "Occurrences",
  more: "Load more",
  remove: "Delete",
  emptyTerms: "No terms yet. Add a term or extract them from the book.",
  find: "Find",
  replacement: "Replace with",
  caseSensitive: "Match case",
  previewChanges: "Preview changes",
  apply: "Apply changes",
  noMatches: "No matches",
  changes: "Changed blocks",
  referenceImport: "Import reference",
  noReference:
    "Import a reference translation, then map its chapters explicitly.",
  unmapped: "Not mapped",
  saveMappings: "Save chapter mapping",
  format: "Format",
  unfinished: "Unfinished chapters",
  reject: "Require complete translations",
  originals: "Include original text",
  exportArchive: "Export project archive",
  chooseDestination: "Choose destination",
  exported: "Export complete",
  instructionHint:
    "Used when this chapter is translated. Saving invalidates its existing translation and dependent context.",
  model: "Model",
  endpoint: "Provider URL",
  apiKey: "API key",
  keyStored: "An API key is configured",
  keyMissing: "No API key configured",
  keyHint: "Leave empty to keep the current key",
  providerHint:
    "Applies to new jobs. Running jobs retain their saved model settings.",
  interfaceLanguage: "Interface language",
  pages: "Pages",
  page: "Page",
  noPages: "No pages",
  mangaUnavailable:
    "Automatic manga processing requires configured recognition, cleanup and lettering models. Page viewing is available.",
  refresh: "Refresh",
  selection: "Scope",
  allChapters: "All chapters",
  selectedChapter: "Current chapter",
  selectChapter: "Select a chapter",
  done: "Done",
  keyboard: "Ctrl/Cmd+S saves · Ctrl/Cmd+K opens commands",
  previewMode: "Interface preview · sample data",
  processing: "Processing",
  queued: "Queued",
  running: "Running",
  succeeded: "Completed",
  failed: "Failed",
  cancelling: "Cancelling",
  cancelled: "Cancelled",
  interrupted: "Interrupted",
  resume: "Resume",
  book_translation: "Translation",
  book_metadata: "Book details",
  book_glossary: "Term extraction",
};
type Key = keyof typeof en;
const ru: Record<Key, string> = {
  mangaModels: "Модели для манги",
  modelDownloadHint:
    "Веса скачиваются с Hugging Face только по запросу и хранятся локально. Закрытие этого окна не прерывает загрузку. После перезапуска приложения продолжите её здесь.",
  modelExperimental:
    "Экспериментальная модель очистки. Скачивание пока не включает обработку манги: ещё предстоит проверить совместимость и качество результата.",
  modelMissing: "Не скачана",
  modelDownloading: "Скачивание",
  modelVerifying: "Проверка файла",
  modelPaused: "Загрузка приостановлена",
  modelDownloaded: "Скачана и проверена",
  modelDownload: "Скачать с Hugging Face",
  modelPause: "Приостановить",
  modelRemove: "Удалить локальные файлы",
  modelUnknown: "Модели нет в каталоге.",
  modelBusy: "Другая загрузка уже выполняется.",
  modelNetwork:
    "Загрузка прервана. Проверьте соединение и продолжите скачивание.",
  modelSizeError:
    "Сервер вернул неожиданный размер или диапазон файла. Модель не установлена.",
  modelHashError: "Файл не прошёл проверку. Скачайте его повторно.",
  modelStorageError:
    "Не удалось открыть кеш моделей. Проверьте свободное место и права доступа.",

  unsupported:
    "Этот формат проекта не поддерживается. Создайте новый проект из исходного файла.",
  commands: "Команды",
  library: "Проекты",
  newProject: "Новый проект",
  importArchive: "Импорт проекта",
  settings: "Настройки",
  book: "Книга",
  manga: "Манга",
  close: "Закрыть",
  cancel: "Отмена",
  save: "Сохранить",
  retry: "Повторить",
  reload: "Отбросить локальные правки и загрузить заново",
  delete: "Удалить проект",
  deleteConfirm: "Удалить проект и его результаты? Исходные файлы сохранятся.",
  welcome: "Рабочее пространство для каждого перевода",
  welcomeHint:
    "Создайте проект книги или манги. Выберите языки один раз, затем работайте с оригиналом и переводом рядом.",
  emptyProjects: "Пока нет проектов",
  open: "Открыть",
  loading: "Загрузка…",
  error: "Не удалось выполнить операцию.",
  noKey: "Добавьте API-ключ в настройках, чтобы начать обработку.",
  conflict:
    "Содержимое изменилось в другом месте. Локальные правки сохранены в редакторе. Загрузите сохранённую версию заново.",
  exists: "Файл с таким именем уже существует. Выберите другое имя.",
  incomplete:
    "Некоторые главы не переведены или требуют проверки. Завершите их либо включите оригиналы непереведённых глав.",
  chooseKind: "Что вы переводите?",
  chooseSource: "Выбрать исходник",
  sourceFile: "Исходный файл",
  name: "Название проекта",
  sourceLanguage: "Язык оригинала",
  targetLanguage: "Язык перевода",
  fixedLanguages: "Эти языки закреплены за проектом и не меняются.",
  create: "Создать проект",
  metadataAfterCreate:
    "Сгенерировать название и аннотацию после создания (использует AI-провайдера)",
  choose: "Выберите…",
  preview: "Предпросмотр импорта",
  bookFormats: "TXT, EPUB, FB2, PDF или ZIP",
  mangaFormats: "CBZ или ZIP с изображениями страниц",
  importWarning: "Проверьте исходник перед созданием проекта.",
  chapters: "Главы",
  chapterFilter: "Найти главу",
  reader: "Текст",
  overview: "Обзор",
  glossary: "Глоссарий",
  reference: "Референс",
  replace: "Поиск и замена",
  export: "Экспорт",
  jobs: "Задания",
  noJobs: "Нет заданий обработки",
  translateChapter: "Перевести главу",
  translateBatch: "Перевести партию",
  bookTitle: "Название книги",
  cover: "Обложка",
  chooseCover: "Выбрать обложку",
  removeCover: "Удалить обложку",
  useGenerated: "Использовать сгенерированное",
  bookPrompt: "Общий промпт книги",
  bookPromptHint:
    "Применяется к следующей партии. Предыдущие переводы сохраняются для проверки. Перед изменением инструкций остановите текущую партию.",

  batchCount: "Глав в партии",
  noEligibleChapters: "В выбранной области нет непереведённых текстовых глав.",
  batchHint:
    "После партии перевод остановится. Проверьте перевод и словарь перед следующим запуском.",
  force: "Заменить существующий перевод",
  instructions: "Инструкции главы",
  original: "Оригинал",
  translation: "Перевод",
  noTranslation: "Переведите главу, чтобы начать редактирование.",
  noChapter: "Выберите главу",
  saving: "Сохранение…",
  saved: "Сохранено",
  unsaved: "Есть несохранённые правки",
  review: "Требует проверки",
  current: "Актуально",
  metadata: "О книге",
  generateMetadata: "Сгенерировать сведения",
  noMetadata: "Сведения ещё не сгенерированы.",
  staleMetadata: "Сведения созданы по предыдущей версии.",
  source: "Исходник",
  author: "Автор",
  summary: "Аннотация",
  extractTerms: "Извлечь термины",
  newTerm: "Добавить термин",
  termSource: "Термин в оригинале",
  termTarget: "Перевод",
  termKind: "Тип",
  pinned: "Закреплён",
  occurrences: "Вхождения",
  more: "Загрузить ещё",
  remove: "Удалить",
  emptyTerms: "Терминов пока нет. Добавьте термин или извлеките их из книги.",
  find: "Найти",
  replacement: "Заменить на",
  caseSensitive: "Учитывать регистр",
  previewChanges: "Показать изменения",
  apply: "Применить изменения",
  noMatches: "Совпадений нет",
  changes: "Изменяемые блоки",
  referenceImport: "Импортировать референс",
  noReference:
    "Импортируйте готовый перевод и сопоставьте его главы с оригиналом.",
  unmapped: "Не сопоставлено",
  saveMappings: "Сохранить сопоставление",
  format: "Формат",
  unfinished: "Незавершённые главы",
  reject: "Только полный перевод",
  originals: "Включить оригинальный текст",
  exportArchive: "Экспорт архива проекта",
  chooseDestination: "Выбрать файл",
  exported: "Экспорт завершён",
  instructionHint:
    "Используются при переводе этой главы. Сохранение пометит её перевод и зависимый контекст для проверки.",
  model: "Модель",
  endpoint: "Адрес провайдера",
  apiKey: "API-ключ",
  keyStored: "API-ключ настроен",
  keyMissing: "API-ключ не задан",
  keyHint: "Оставьте пустым, чтобы сохранить текущий ключ",
  providerHint:
    "Для новых заданий. Запущенные задания сохраняют свои настройки модели.",
  interfaceLanguage: "Язык интерфейса",
  pages: "Страницы",
  page: "Страница",
  noPages: "Нет страниц",
  mangaUnavailable:
    "Для автоматической обработки манги нужны настроенные модели распознавания, очистки и набора текста. Просмотр страниц доступен.",
  refresh: "Обновить",
  selection: "Область",
  allChapters: "Все главы",
  selectedChapter: "Текущая глава",
  selectChapter: "Выберите главу",
  done: "Готово",
  keyboard: "Ctrl/Cmd+S — сохранить · Ctrl/Cmd+K — команды",
  previewMode: "Предпросмотр интерфейса · пример данных",
  processing: "Обработка",
  queued: "В очереди",
  running: "Выполняется",
  succeeded: "Завершено",
  failed: "Ошибка",
  cancelling: "Отменяется",
  cancelled: "Отменено",
  interrupted: "Прервано",
  resume: "Продолжить",
  book_translation: "Перевод",
  book_metadata: "Сведения о книге",
  book_glossary: "Извлечение терминов",
};
const zh: Record<Key, string> = {
  mangaModels: "漫画模型",
  modelDownloadHint:
    "仅按需从 Hugging Face 下载权重并缓存到本地。关闭此窗口不会中断下载；重启应用后可在此继续。",
  modelExperimental:
    "实验性清理模型。下载不代表漫画处理已可用；仍需验证运行时兼容性和图像质量。",
  modelMissing: "未下载",
  modelDownloading: "下载中",
  modelVerifying: "正在校验",
  modelPaused: "下载已暂停",
  modelDownloaded: "已下载并校验",
  modelDownload: "从 Hugging Face 下载",
  modelPause: "暂停下载",
  modelRemove: "删除本地文件",
  modelUnknown: "目录中没有此模型。",
  modelBusy: "另一个下载正在进行。",
  modelNetwork: "下载已中断。请检查连接后继续。",
  modelSizeError: "服务器返回了意外的文件大小或范围。模型未安装。",
  modelHashError: "文件校验失败，请重新下载。",
  modelStorageError: "无法访问模型缓存。请检查磁盘空间和文件权限。",

  unsupported: "不支持此项目格式。请从源文件创建新项目。",
  commands: "命令",
  library: "项目",
  newProject: "新建项目",
  importArchive: "导入项目",
  settings: "设置",
  book: "书籍",
  manga: "漫画",
  close: "关闭",
  cancel: "取消",
  save: "保存",
  retry: "重试",
  reload: "放弃本地修改并重新加载",
  delete: "删除项目",
  deleteConfirm: "删除项目及其结果？原始文件将保留。",
  welcome: "每份译作都有自己的工作空间",
  welcomeHint: "创建书籍或漫画项目。一次选定语言，随后并排处理原文与译文。",
  emptyProjects: "暂无项目",
  open: "打开",
  loading: "加载中…",
  error: "操作未能完成。",
  noKey: "请在设置中添加 API 密钥以开始处理。",
  conflict:
    "内容已在别处更改。本地修改仍保留在编辑器中，可重新加载已保存的版本。",
  exists: "同名文件已存在。请选择其他名称。",
  incomplete: "部分章节未翻译或需要检查。请完成翻译，或选择包含原文。",
  chooseKind: "要翻译什么？",
  chooseSource: "选择源文件",
  sourceFile: "源文件",
  name: "项目名称",
  sourceLanguage: "原文语言",
  targetLanguage: "译文语言",
  fixedLanguages: "语言选定后不能更改。",
  create: "创建项目",
  metadataAfterCreate: "创建后生成标题和简介（使用 AI 服务）",
  choose: "请选择…",
  preview: "导入预览",
  bookFormats: "TXT、EPUB、FB2、PDF 或 ZIP",
  mangaFormats: "包含页面图片的 CBZ 或 ZIP",
  importWarning: "创建项目之前请检查源文件。",
  chapters: "章节",
  chapterFilter: "查找章节",
  reader: "正文",
  overview: "概览",
  glossary: "术语表",
  reference: "参考译文",
  replace: "查找与替换",
  export: "导出",
  jobs: "任务",
  noJobs: "暂无处理任务",
  translateChapter: "翻译章节",
  translateBatch: "翻译本批次",
  bookTitle: "书名",
  cover: "封面",
  chooseCover: "选择封面",
  removeCover: "移除封面",
  useGenerated: "使用生成值",
  bookPrompt: "全书翻译说明",
  bookPromptHint:
    "应用于下一批次。已有译文将保留供检查。修改说明前请停止当前批次。",

  batchCount: "每批章节数",
  noEligibleChapters: "所选范围内没有待翻译的文本章节。",
  batchHint: "本批次完成后停止。开始下一批前请检查译文和术语表。",
  force: "替换现有译文",
  instructions: "章节指令",
  original: "原文",
  translation: "译文",
  noTranslation: "翻译此章节后即可编辑。",
  noChapter: "请选择章节",
  saving: "保存中…",
  saved: "已保存",
  unsaved: "存在未保存的修改",
  review: "需要检查",
  current: "当前版本",
  metadata: "书籍信息",
  generateMetadata: "生成信息",
  noMetadata: "尚未生成书籍信息。",
  staleMetadata: "信息基于旧版本生成。",
  source: "来源",
  author: "作者",
  summary: "简介",
  extractTerms: "提取术语",
  newTerm: "添加术语",
  termSource: "原文术语",
  termTarget: "译文",
  termKind: "类型",
  pinned: "固定",
  occurrences: "出现次数",
  more: "加载更多",
  remove: "删除",
  emptyTerms: "暂无术语。可以手动添加或从书中提取。",
  find: "查找",
  replacement: "替换为",
  caseSensitive: "区分大小写",
  previewChanges: "预览修改",
  apply: "应用修改",
  noMatches: "没有匹配项",
  changes: "修改的文本块",
  referenceImport: "导入参考译文",
  noReference: "导入参考译文并手动对应章节。",
  unmapped: "未对应",
  saveMappings: "保存对应关系",
  format: "格式",
  unfinished: "未完成章节",
  reject: "仅允许完整译文",
  originals: "包含原文",
  exportArchive: "导出项目归档",
  chooseDestination: "选择目标文件",
  exported: "导出完成",
  instructionHint: "翻译该章节时使用。保存后现有译文和相关上下文将需要检查。",
  model: "模型",
  endpoint: "服务地址",
  apiKey: "API 密钥",
  keyStored: "已配置 API 密钥",
  keyMissing: "未配置 API 密钥",
  keyHint: "留空以保留当前密钥",
  providerHint: "适用于新任务。正在运行的任务保留原有模型设置。",
  interfaceLanguage: "界面语言",
  pages: "页面",
  page: "页",
  noPages: "暂无页面",
  mangaUnavailable:
    "漫画自动处理需要配置识别、清理和排版模型。目前可以浏览页面。",
  refresh: "刷新",
  selection: "范围",
  allChapters: "全部章节",
  selectedChapter: "当前章节",
  selectChapter: "选择章节",
  done: "完成",
  keyboard: "Ctrl/Cmd+S 保存 · Ctrl/Cmd+K 打开命令",
  previewMode: "界面预览 · 示例数据",
  processing: "处理中",
  queued: "排队中",
  running: "运行中",
  succeeded: "已完成",
  failed: "失败",
  cancelling: "正在取消",
  cancelled: "已取消",
  interrupted: "已中断",
  resume: "继续",
  book_translation: "翻译",
  book_metadata: "书籍信息",
  book_glossary: "提取术语",
};
export type T = (key: Key) => string;
export const translator =
  (lang: Lang): T =>
  (key) =>
    ({ en, ru, zh })[lang][key];
export function errorText(error: unknown, t: T): string {
  const e = error as {
    code?: string;
    messageKey?: string;
    params?: {
      field?: string;
    };
  } | null;
  if (e?.code === "unsupported_version") return t("unsupported");
  if (e?.code === "revision_conflict") return t("conflict");
  if (e?.messageKey === "errors.apiKeyRequired") return t("noKey");
  if (e?.params?.field === "noEligibleChapters") return t("noEligibleChapters");
  if (e?.params?.field === "destinationExists") return t("exists");
  if (e?.params?.field === "incompleteTranslation") return t("incomplete");
  return error instanceof Error
    ? error.message
    : typeof error === "string"
      ? error
      : t("error");
}
export const languages = [
  "en",
  "ru",
  "zh",
  "ja",
  "ko",
  "de",
  "fr",
  "es",
  "it",
  "pt",
];
export const languageName = (code: string, lang: Lang) => {
  try {
    return new Intl.DisplayNames([lang], { type: "language" }).of(code) ?? code;
  } catch {
    return code;
  }
};
