import type { Lang } from "../i18n";
const en = {
  narration: "Narration",
  audioEngine: "Model in memory",
  audioEngineUnloaded: "Not loaded",
  audioEngineLoading: "Loading model…",
  audioEngineReady: "Ready",
  audioLoad: "Load model",
  audioUnload: "Unload model",
  audioEngineHint: "Load once on the selected device and reuse the model for chapters and new jobs. It stays in memory until unloaded or the app closes. Create MP3 also loads it automatically when needed.",
  audioPausing: "Pausing…",
  audioPauseHint: "Finishing the current fragment; the model stays loaded.",
  audioIntro: "Create an audiobook locally. Each chapter is saved as an MP3, with a playlist for the whole book.",
  audioModel: "Voice model",
  audioReady: "Downloaded",
  audioRuntimeMissing: "The speech engine is missing from this build. Install a build with the narration runtime.",
  audioDownload: "Download / resume model",
  audioDownloadFailed: "Download failed. Check your connection and resume.",
  audioVerifying: "Verifying downloaded files…",
  audioPause: "Pause",
  audioResume: "Resume saved text",
  audioOptions: "What to narrate",
  audioText: "Text",
  audioTranslation: "Translation",
  audioOriginal: "Original",
  audioRange: "Chapter range",
  audioFrom: "From chapter",
  audioTo: "Through chapter",
  audioVoice: "Voice",
  audioDevice: "Compute device",
  audioAuto: "Automatic (GPU if available)",
  audioCpuHint: "CPU generation can be slow. Try one chapter first. CUDA requires a runtime built with NVIDIA support. All voices support Russian; pronunciation varies.",
  audioStart: "Create MP3",
  audioJobs: "Audio jobs",
  audioEmptyJobs: "Choose a chapter and voice to start. Translation must be complete for the selected chapters.",
  audioRunning: "Generating",
  audioPaused: "Paused",
  audioInterrupted: "Interrupted",
  audioFailed: "Failed",
  audioFinished: "Ready",
  audioProgress: "Narration progress",
  audioListen: "Listen",
  audioPreviewRefresh: "Latest fragment",
  audioPreviewSave: "Save fragment as MP3",
  audioPreviewSaved: "Fragment saved as MP3.",
  audioPreviewHint: "Listen to up to 30 seconds of the latest saved audio, even while narration is running or paused.",
  audioPreviewWaiting: "The player will be available after the first fragment is ready. No need to wait for the whole chapter.",
  audioPreviewUnavailable: "No saved audio is available yet. Wait for the first fragment or resume narration.",
  audioPlaybackError: "Could not play the fragment. Try loading the latest fragment again.",
  audioPreparing: "Preparing the voice model…",
  audioSave: "Save MP3 chapters",
  audioSaved: "MP3 chapters and playlist saved.",
  audioOpenFolder: "Open folder",
  audioBusy: "Another narration is running. Pause it first.",
  audioModels: "Download all voice model files before starting.",
  audioLanguage: "This language is not supported by Qwen3-TTS.",
  audioIncomplete: "Selected chapters have missing translated text or titles. Complete the translation, or select the original.",
  audioEmpty: "No text in the selected chapters.",
  audioCuda: "NVIDIA CUDA is unavailable. Choose CPU or install a CUDA runtime.",
  audioMemory: "Not enough memory for speech generation. Close other applications or try CPU.",
  audioWorker: "The speech engine stopped. Resume to retry from saved progress.",
  audioStorage: "Could not read or save audio. Check free disk space and folder access.",
  audioOutput: "The model returned invalid audio. Resume to retry this fragment.",
  audioTooLong: "A fragment reached the generation limit. Its audio was not saved; resume to retry.",
  audioVersion: "This audio job uses an unsupported version. Create a new job.",
  audioNotFinished: "Wait for narration to finish before exporting.",

  previousPage: "Previous page",
  nextPage: "Next page",
  openBook: "Open book",
  chooseBook: "Choose book",
  importBookSettings: "Translation settings",
  volumeTitle: "Volume title",
  volumeTitleWorking: "Processing…",
  chapterEditBusy: "This chapter is in use while processing it or the next chapter. Editing is temporarily locked.",
  deleteChapter: "Delete chapter",
  deleteChapterConfirm: "Delete “{title}” from this project? Its source content, saved translations and reference mapping will be removed. This cannot be undone. The original book file is kept.",
  chapterDeleteBusy: "Stop the project's active job before deleting a chapter.",
  chapterDeleted: "This chapter has been deleted. Start a new job using the remaining chapters.",
  metadataLanguageError: "The model returned book details in the wrong language. Please retry.",
  glossaryOutputError: "Glossary extraction failed: the model returned invalid terms or an incomplete response. Retry the job.",
  providerTransportError: "Could not reach the translation provider. Check the connection and provider timeout.",
  providerHttpError: "The translation provider rejected the request.",
  providerResponseError: "The translation provider returned an invalid response.",
  translationOutputError: "The model did not return all required translation segments. Retry the job.",
  glossaryFinishError: "The glossary response was interrupted or exceeded the output token limit.",
  glossaryJsonError: "The glossary response does not match the required JSON format.",

  unsupported:
    "This project uses an unsupported format. Create a new project from its source.",
  commands: "Commands",
  library: "Projects",
  importArchive: "Import project",
  settings: "Settings",
  book: "Book",
  close: "Close",
  cancel: "Cancel",
  save: "Save",
  retry: "Retry",
  reload: "Discard local edits and reload",
  delete: "Delete project",
  deleteConfirm:
    "Delete this project and its results? Source files will be kept.",
  welcome: "A workspace for every translation",
  welcomeHint:
    "Choose a book and its translation languages, then work with the original and translation side by side.",
  emptyProjects: "No projects yet",
  open: "Open",
  assistantApplied: "Changes applied. No further confirmation is needed.",
  assistantConflict: "This proposal is out of date because the chapter or settings changed. Ask the assistant to prepare changes again. Previously applied changes are kept.",
  diagnostics: "Diagnostics",
  fullLogging: "Full diagnostic logging",
  fullLoggingHint: "Applies immediately. Records processing stages, runtime checks and command timings. API keys, book text and images are not logged. Save the log archive after reproducing the issue.",
  exportDiagnostics: "Save diagnostic logs",
  loading: "Loading…",
  exporting: "Exporting…",
  error: "The operation could not be completed.",
  noKey: "Add an API key in Settings to start processing.",
  conflict:
    "This content changed elsewhere. Your local edits are kept. Reload to use the saved version.",
  exists: "A file with this name already exists. Choose another name.",
  incomplete:
    "Some chapters need translation or review. Complete them, or choose originals for unfinished chapters.",
  chooseSource: "Choose source",
  sourceFile: "Source file",
  name: "Book name",
  sourceLanguage: "Original language",
  targetLanguage: "Translation language",
  defaultTargetLanguage: "Default translation language",
  defaultTargetLanguageHint: "Used when opening new books.",
  fixedLanguages: "These languages are fixed for this book.",
  metadataAfterCreate:
    "Translate title and author and create an annotation after import (AI)",
  choose: "Choose…",
  preview: "Import preview",
  bookFormats: "TXT, EPUB, FB2, PDF or ZIP",
  importWarning: "Check the imported source before translating.",
  chapters: "Chapters",
  discardConfirm: "Discard unsaved changes and reload the saved translation?",
  jobChapter: "Chapter",
  jobStages: "Stages",
  jobContext: "Updating context",
  chapterFilter: "Find a chapter",
  reader: "Text",
  overview: "Overview",
  glossary: "Glossary",
  reference: "Reference",
  chapterStatusFilter: "Chapter status",
  chapterFailed: "Translation failed",
  chapterInProgress: "Translating",
  chapterDone: "Translated",
  chapterSkipped: "No text to translate",
  chapterPending: "Awaiting translation",
  languageIssues: "Untranslated or foreign-language fragments",

  originReference: "From reference",
  originManual: "Manual",
  originModel: "Model",
  replace: "Find and replace",
  export: "Export",
  jobs: "Jobs",
  clearFinishedJobs: "Clear finished jobs",
  noJobs: "No processing jobs",
  assistantSendHint: "Enter to send · Shift+Enter for a new line",
  translationOptions: "Translation options",
  translationProgress: "Translation progress",
  remainingTime: "Approx. remaining",
  estimatingTime: "Estimating time…",
  etaHours: "h",
  etaMinutes: "min",
  etaSeconds: "s",
  translateChapter: "Translate chapter",
  translatePage: "Translate",
  translateBatch: "Translate batch",
  bookTitle: "Book title",
  assistant: "AI assistant",
  assistantHint:
    "Current chapter, book instructions and up to 100 glossary terms. Proposals expire after 30 minutes or an app restart.",
  you: "You",
  actionResult: "Action result",
  before: "Before",
  after: "After",
  decline: "Reject",
  assistantMessage: "Message",
  assistantExample:
    "Check the names in this chapter and suggest glossary corrections.",
  assistantAutoRun: "Automatically apply actions proposed for this request",
  send: "Send",

  cover: "Cover",
  chooseCover: "Choose cover",
  removeCover: "Remove cover",
  useGenerated: "Use generated value",
  bookPrompt: "Book translation instructions",
  bookPromptHint:
    "Applied to the next batch. Earlier translations remain available for review. Stop an active batch before changing its instructions.",

  automaticGlossary: "The glossary updates automatically after each translated chapter.",
  referenceGlossaryHint: "Importing a reference or changing chapter mappings automatically updates the glossary for those chapters.",
  batchCount: "Chapters per batch",
  chooseFolder: "Choose image folder",
  providerProfiles: "Model profiles",
  projectProviders: "Project models",
  defaultProvider: "Default provider",
  regionEditHint:
    "Drag regions to move them; drag the corner to resize. Apply rebuilds cleanup and text from the original, using the current translations. Edited rectangles are erased in full.",
  applyRegions: "Apply",

  noProviderProfiles:
    "No profiles yet. Enter a name, API model, endpoint and key, then save the profile. It will appear in the selectors below.",
  missingProfile: "Profile unavailable",
  newProfile: "New profile",
  profileName: "Profile name",
  bookSearch: "Search book",
  searchText: "Text to find",
  moreResults: "More results",

  saveProfile: "Save profile",
  applyRoles: "Save project models",
  bookTranslationProfile: "Book translation",
  assistantProfile: "AI assistant",
  profileKeyHint:
    "Changing the endpoint clears the old key unless you enter a replacement.",
  temperature: "Temperature",
  contextTokens: "Context window (tokens)",
  outputTokens: "Maximum output tokens",
  fileMenu: "File",
  helpMenu: "Help",
  about: "About",
  version: "Version",
  build: "Build",
  builtAt: "Built at",
  distributionNotice: "Free and open-source software · MIT License.",
  replaceMode: "Replace",
  replaceTranslationOnly: "Replace in translated text",
  noEligibleChapters: "No untranslated text chapters in this selection.",
  batchHint:
    "Stops after this batch. Review translations and glossary before starting the next one.",
  force: "Replace existing translations",
  instructions: "Chapter instructions",
  original: "Original",
  translation: "Translation",
  noTranslation: "Translate this chapter to start editing.",
  noChapter: "Choose a chapter",
  saving: "Saving…",
  saved: "Saved",
  unsaved: "Unsaved changes",
  review: "Needs review",
  current: "Current",
  metadata: "Book details",
  generateSummary: "Generate annotation with AI",
  generateMetadata: "Translate title and author",
  noMetadata: "No generated details yet.",
  staleMetadata: "Details were generated from an earlier version.",
  source: "Source",
  author: "Author",
  summary: "Summary",
  extractTerms: "Extract terms",
  extractionBatchHint:
    "Process the next eligible chapters. Previously processed chapters are skipped unless repeated extraction is enabled.",
  repeatExtraction: "Extract previously processed chapters again",
  newTerm: "Add term",
  glossarySearch: "Find a source or translated term (case-sensitive)",
  pinnedOnly: "Pinned only",
  totalTerms: "Total terms",
  termsFound: "Terms found",
  noMatchingTerms: "No terms match these filters.",
  termSource: "Original term",
  termTarget: "Translation",
  termKind: "Type",
  glossarySearchShort: "Search terms…",
  kindPerson: "Person",
  kindLocation: "Location",
  kindOrganization: "Organization",
  kindTerm: "Term",
  pinned: "Pinned",
  occurrences: "Occurrences",
  more: "Load more",
  remove: "Delete",
  emptyTerms: "No terms yet. Add a term or extract them from the book.",
  find: "Find",
  replacement: "Replace with",
  caseSensitive: "Match case",
  previewChanges: "Preview changes",
  apply: "Apply changes",
  noMatches: "No matches",
  changes: "Changed blocks",
  referenceImport: "Import reference",
  mappingHint:
    "Select an original chapter, then its reference chapter. Save the mappings when finished.",
  removeMapping: "Remove mapping",
  noReference:
    "Import a reference translation to fill untranslated chapters automatically.",
  unmapped: "Not mapped",
  saveMappings: "Save chapter mapping",
  format: "Format",
  unfinished: "Export content",
  translatedOnly: "Translated chapters",
  translatedOnlyHint: "Chapters without a saved translation are skipped. The cover and image-only chapters up to the last translated chapter are preserved.",
  noTranslatedChapters: "No saved translations or image-only chapters in this selection.",
  reject: "Require complete translations",
  originals: "Whole book with untranslated originals",
  exportArchive: "Export project archive",
  chooseDestination: "Choose destination",
  exported: "Export complete",
  instructionHint:
    "Used when this chapter is translated. Saving invalidates its existing translation and dependent context.",
  model: "Model",
  endpoint: "Provider URL",
  apiKey: "API key",
  keyStored: "An API key is configured",
  keyMissing: "No API key configured",
  keyHint: "Leave empty to keep the current key",
  providerHint:
    "Applies to new jobs. Running jobs retain their saved model settings.",
  interfaceLanguage: "Interface language",
  refresh: "Refresh",
  selection: "Scope",
  allChapters: "All chapters",
  selectedChapter: "Current chapter",
  selectChapter: "Select a chapter",
  done: "Done",
  keyboard: "Ctrl/Cmd+S saves · Ctrl/Cmd+K opens commands",
  previewMode: "Interface preview · sample data",
  processing: "Processing",
  queued: "Queued",
  running: "Running",
  succeeded: "Completed",
  failed: "Failed",
  cancelling: "Cancelling",
  cancelled: "Cancelled",
  interrupted: "Interrupted",
  resume: "Resume",
  book_translation: "Translation",
  book_metadata: "Book details",
  book_title: "Translate title",
  book_retarget: "Correct glossary terms",
  retarget: "Correct in translations",
  retargetFragments: "Matching fragments",
  retargetHint:
    "The term is saved. Correct matching fragments in this many chapters, including summaries? Nothing runs until you confirm.",
  translateTitle: "Translate title",
  translatedChapterTitle: "Translated chapter title",
  importScanning: "Reading file or folder…",
  importFinalizing: "Finishing import…",
  importCreating: "Opening book…",
  importProgress: "Import progress",
  importWorking: "The application is working. Large files may take a while.",
  book_glossary: "Term extraction",
};
type Key = keyof typeof en;
const ru: Record<Key, string> = {
  narration: "Озвучка",
  audioEngine: "Модель в памяти",
  audioEngineUnloaded: "Не загружена",
  audioEngineLoading: "Загрузка модели…",
  audioEngineReady: "Готова",
  audioLoad: "Загрузить модель",
  audioUnload: "Выгрузить модель",
  audioEngineHint: "Загрузите модель на выбранном устройстве один раз для всех глав и следующих заданий. Она останется в памяти до выгрузки или закрытия приложения. «Создать MP3» тоже загружает её автоматически при необходимости.",
  audioPausing: "Останавливается…",
  audioPauseHint: "Завершаем текущий фрагмент; модель останется в памяти.",
  audioIntro: "Создайте аудиокнигу на своём компьютере. Каждая глава сохраняется в MP3, вся книга — с плейлистом.",
  audioModel: "Модель озвучки",
  audioReady: "Скачана",
  audioRuntimeMissing: "В этой сборке отсутствует движок озвучки. Установите сборку с движком озвучки.",
  audioDownload: "Скачать / продолжить загрузку",
  audioDownloadFailed: "Загрузка не удалась. Проверьте соединение и продолжите загрузку.",
  audioVerifying: "Проверяем скачанные файлы…",
  audioPause: "Пауза",
  audioResume: "Продолжить сохранённый текст",
  audioOptions: "Что озвучить",
  audioText: "Текст",
  audioTranslation: "Перевод",
  audioOriginal: "Оригинал",
  audioRange: "Диапазон глав",
  audioFrom: "С главы",
  audioTo: "По главу",
  audioVoice: "Голос",
  audioDevice: "Устройство",
  audioAuto: "Автоматически (GPU при наличии)",
  audioCpuHint: "На CPU генерация может быть медленной. Начните с одной главы. Для CUDA нужна сборка движка с поддержкой NVIDIA. Все голоса поддерживают русский, произношение различается.",
  audioStart: "Создать MP3",
  audioJobs: "Задания озвучки",
  audioEmptyJobs: "Выберите главу и голос. Для озвучки перевода выбранные главы должны быть переведены полностью.",
  audioRunning: "Озвучивается",
  audioPaused: "На паузе",
  audioInterrupted: "Прервано",
  audioFailed: "Ошибка",
  audioFinished: "Готово",
  audioProgress: "Прогресс озвучки",
  audioListen: "Прослушать",
  audioPreviewRefresh: "Последний фрагмент",
  audioPreviewSave: "Сохранить фрагмент в MP3",
  audioPreviewSaved: "Фрагмент сохранён в MP3.",
  audioPreviewHint: "До 30 секунд последнего готового звука. Можно слушать во время озвучки и на паузе.",
  audioPreviewWaiting: "Плеер станет доступен после первого готового фрагмента. Ждать всю главу не нужно.",
  audioPreviewUnavailable: "Готового звука пока нет. Дождитесь первого фрагмента или продолжите озвучку.",
  audioPlaybackError: "Не удалось воспроизвести фрагмент. Попробуйте загрузить последний фрагмент ещё раз.",
  audioPreparing: "Подготавливаем модель голоса…",
  audioSave: "Сохранить главы в MP3",
  audioSaved: "MP3 глав и плейлист сохранены.",
  audioOpenFolder: "Открыть папку",
  audioBusy: "Уже выполняется озвучка. Сначала остановите её.",
  audioModels: "Сначала скачайте все файлы модели озвучки.",
  audioLanguage: "Этот язык не поддерживается Qwen3-TTS.",
  audioIncomplete: "В выбранных главах отсутствует перевод текста или заголовка. Завершите перевод или выберите оригинал.",
  audioEmpty: "В выбранных главах нет текста.",
  audioCuda: "NVIDIA CUDA недоступна. Выберите CPU или установите движок с поддержкой CUDA.",
  audioMemory: "Недостаточно памяти для озвучки. Закройте другие приложения или попробуйте CPU.",
  audioWorker: "Движок озвучки остановился. Продолжите задание с сохранённого места.",
  audioStorage: "Не удалось прочитать или сохранить аудио. Проверьте место на диске и доступ к папке.",
  audioOutput: "Модель вернула некорректное аудио. Продолжите, чтобы повторить этот фрагмент.",
  audioTooLong: "Фрагмент достиг лимита генерации. Его аудио не сохранено; продолжите для повторной попытки.",
  audioVersion: "Это задание озвучки создано в неподдерживаемой версии. Создайте новое.",
  audioNotFinished: "Дождитесь окончания озвучки перед сохранением.",

  previousPage: "Предыдущая страница",
  nextPage: "Следующая страница",
  openBook: "Открыть книгу",
  chooseBook: "Выбрать книгу",
  importBookSettings: "Параметры перевода",
  volumeTitle: "Название тома",
  volumeTitleWorking: "Обработка…",
  chapterEditBusy: "Глава используется при обработке текущей или следующей главы. Редактирование временно заблокировано.",
  deleteChapter: "Удалить главу",
  deleteChapterConfirm: "Удалить «{title}» из проекта? Будут удалены содержимое главы, сохранённые переводы и сопоставление с референсом. Отменить удаление нельзя. Исходный файл книги сохранится.",
  chapterDeleteBusy: "Перед удалением главы остановите обработку проекта.",
  chapterDeleted: "Глава удалена. Запустите новое задание для оставшихся глав.",
  metadataLanguageError: "Модель вернула описание книги не на языке перевода. Повторите задание.",
  glossaryOutputError: "Не удалось извлечь глоссарий: модель вернула некорректные термины или неполный ответ. Повторите задание.",
  providerTransportError: "Не удалось связаться с провайдером перевода. Проверьте соединение и тайм-аут провайдера.",
  providerHttpError: "Провайдер перевода отклонил запрос.",
  providerResponseError: "Провайдер перевода вернул некорректный ответ.",
  translationOutputError: "Модель не вернула все необходимые фрагменты перевода. Повторите задание.",
  glossaryFinishError: "Ответ с глоссарием прерван или превысил лимит выходных токенов.",
  glossaryJsonError: "Ответ с глоссарием не соответствует требуемому формату JSON.",

  unsupported:
    "Этот формат проекта не поддерживается. Создайте новый проект из исходного файла.",
  commands: "Команды",
  library: "Проекты",
  importArchive: "Импорт проекта",
  settings: "Настройки",
  book: "Книга",
  close: "Закрыть",
  cancel: "Отмена",
  save: "Сохранить",
  retry: "Повторить",
  reload: "Отбросить локальные правки и загрузить заново",
  delete: "Удалить проект",
  deleteConfirm: "Удалить проект и его результаты? Исходные файлы сохранятся.",
  welcome: "Рабочее пространство для каждого перевода",
  welcomeHint:
    "Выберите книгу и языки перевода, затем работайте с оригиналом и переводом рядом.",
  emptyProjects: "Пока нет проектов",
  open: "Открыть",
  assistantApplied: "Изменения применены. Повторное подтверждение не требуется.",
  assistantConflict: "Предложение устарело: глава или настройки изменились. Попросите ассистента подготовить правки заново. Уже применённые изменения сохранены.",
  diagnostics: "Диагностика",
  fullLogging: "Полное диагностическое логирование",
  fullLoggingHint: "Применяется сразу. Записывает этапы обработки, проверки компонентов и время команд. API-ключи, текст книг и изображения в лог не попадают. После воспроизведения ошибки сохраните архив логов.",
  exportDiagnostics: "Сохранить логи диагностики",
  loading: "Загрузка…",
  exporting: "Выгрузка…",
  error: "Не удалось выполнить операцию.",
  noKey: "Добавьте API-ключ в настройках, чтобы начать обработку.",
  conflict:
    "Содержимое изменилось в другом месте. Локальные правки сохранены в редакторе. Загрузите сохранённую версию заново.",
  exists: "Файл с таким именем уже существует. Выберите другое имя.",
  incomplete:
    "Некоторые главы не переведены или требуют проверки. Завершите их либо включите оригиналы непереведённых глав.",
  chooseSource: "Выбрать исходник",
  sourceFile: "Исходный файл",
  name: "Название книги",
  sourceLanguage: "Язык оригинала",
  targetLanguage: "Язык перевода",
  defaultTargetLanguage: "Язык перевода по умолчанию",
  defaultTargetLanguageHint: "Подставляется при открытии новых книг.",
  fixedLanguages: "Эти языки закреплены за книгой и не меняются.",
  metadataAfterCreate:
    "Перевести название и автора, создать аннотацию после импорта (ИИ)",
  choose: "Выберите…",
  preview: "Предпросмотр импорта",
  bookFormats: "TXT, EPUB, FB2, PDF или ZIP",
  importWarning: "Проверьте импортированный оригинал перед переводом.",
  chapters: "Главы",
  discardConfirm:
    "Отменить несохранённые изменения и загрузить сохранённый перевод?",
  jobChapter: "Глава",
  jobStages: "Этапы",
  jobContext: "Обновление контекста",
  chapterFilter: "Найти главу",
  reader: "Текст",
  overview: "Обзор",
  glossary: "Глоссарий",
  reference: "Референс",
  chapterStatusFilter: "Статус глав",
  chapterFailed: "Ошибка перевода",
  chapterInProgress: "Переводится",
  chapterDone: "Переведено",
  chapterSkipped: "Нет текста для перевода",
  chapterPending: "Ожидает перевода",
  languageIssues: "Непереведённые или иноязычные фрагменты",

  originReference: "Из референса",
  originManual: "Вручную",
  originModel: "Модель",
  replace: "Поиск и замена",
  export: "Экспорт",
  jobs: "Задания",
  clearFinishedJobs: "Очистить завершённые задания",
  noJobs: "Нет заданий обработки",
  assistantSendHint: "Enter — отправить · Shift+Enter — новая строка",
  translationOptions: "Параметры перевода",
  translationProgress: "Прогресс перевода",
  remainingTime: "Примерно осталось",
  estimatingTime: "Оцениваем время…",
  etaHours: "ч",
  etaMinutes: "мин",
  etaSeconds: "с",
  translateChapter: "Перевести главу",
  translatePage: "Перевести",
  translateBatch: "Перевести партию",
  bookTitle: "Название книги",
  assistant: "ИИ-ассистент",
  assistantHint:
    "Контекст: текущая глава, общий промпт и до 100 терминов словаря. Предложения действуют 30 минут и до перезапуска приложения.",
  you: "Вы",
  actionResult: "Результат действия",
  before: "До",
  after: "После",
  decline: "Отклонить",
  assistantMessage: "Сообщение",
  assistantExample:
    "Проверь имена в этой главе и предложи исправления словаря.",
  assistantAutoRun:
    "Автоматически применять предложенные действия для этого запроса",
  send: "Отправить",

  cover: "Обложка",
  chooseCover: "Выбрать обложку",
  removeCover: "Удалить обложку",
  useGenerated: "Использовать сгенерированное",
  bookPrompt: "Общий промпт книги",
  bookPromptHint:
    "Применяется к следующей партии. Предыдущие переводы сохраняются для проверки. Перед изменением инструкций остановите текущую партию.",

  automaticGlossary: "Словарь пополняется автоматически после каждой переведённой главы.",
  referenceGlossaryHint: "При импорте референса или изменении сопоставления глав словарь автоматически пополняется по этим главам.",
  batchCount: "Глав в партии",
  chooseFolder: "Выбрать папку изображений",
  providerProfiles: "Профили моделей",
  projectProviders: "Модели проекта",
  defaultProvider: "Провайдер по умолчанию",
  regionEditHint:
    "Перемещайте рамки и тяните за угол. «Применить» очистит исправленные области целиком и заново наложит перевод.",
  applyRegions: "Применить",

  noProviderProfiles:
    "Профилей пока нет. Укажите название, модель API, адрес и ключ, затем сохраните профиль. Он появится в списках ниже.",
  missingProfile: "Профиль недоступен",
  newProfile: "Новый профиль",
  profileName: "Название профиля",
  bookSearch: "Поиск по книге",
  searchText: "Найти текст",
  moreResults: "Ещё результаты",

  saveProfile: "Сохранить профиль",
  applyRoles: "Сохранить модели проекта",
  bookTranslationProfile: "Перевод книги",
  assistantProfile: "ИИ-ассистент",
  profileKeyHint:
    "При смене адреса старый ключ удаляется, если не указан новый.",
  temperature: "Температура",
  contextTokens: "Размер контекста (токены)",
  outputTokens: "Максимум токенов ответа",
  fileMenu: "Файл",
  helpMenu: "Справка",
  about: "О программе",
  version: "Версия",
  build: "Сборка",
  builtAt: "Дата сборки",
  distributionNotice: "Свободное ПО с открытым исходным кодом · Лицензия MIT.",
  replaceMode: "Замена",
  replaceTranslationOnly: "Замена в тексте перевода",
  noEligibleChapters: "В выбранной области нет непереведённых текстовых глав.",
  batchHint:
    "После партии перевод остановится. Проверьте перевод и словарь перед следующим запуском.",
  force: "Заменить существующий перевод",
  instructions: "Инструкции главы",
  original: "Оригинал",
  translation: "Перевод",
  noTranslation: "Переведите главу, чтобы начать редактирование.",
  noChapter: "Выберите главу",
  saving: "Сохранение…",
  saved: "Сохранено",
  unsaved: "Есть несохранённые правки",
  review: "Требует проверки",
  current: "Актуально",
  metadata: "О книге",
  generateSummary: "Сгенерировать аннотацию ИИ",
  generateMetadata: "Перевести название и автора",
  noMetadata: "Сведения ещё не сгенерированы.",
  staleMetadata: "Сведения созданы по предыдущей версии.",
  source: "Исходник",
  author: "Автор",
  summary: "Аннотация",
  extractTerms: "Извлечь термины",
  extractionBatchHint:
    "Обработать следующие подходящие главы. Уже обработанные пропускаются, если не включено повторное извлечение.",
  repeatExtraction: "Повторно извлечь из обработанных глав",
  newTerm: "Добавить термин",
  glossarySearch: "Поиск по оригиналу или переводу термина (с учётом регистра)",
  pinnedOnly: "Только закреплённые",
  totalTerms: "Всего терминов",
  termsFound: "Найдено терминов",
  noMatchingTerms: "По заданным условиям термины не найдены.",
  termSource: "Термин в оригинале",
  termTarget: "Перевод",
  termKind: "Тип",
  glossarySearchShort: "Поиск по словарю…",
  kindPerson: "Персонаж",
  kindLocation: "Место",
  kindOrganization: "Организация",
  kindTerm: "Термин",
  pinned: "Закреплён",
  occurrences: "Вхождения",
  more: "Загрузить ещё",
  remove: "Удалить",
  emptyTerms: "Терминов пока нет. Добавьте термин или извлеките их из книги.",
  find: "Найти",
  replacement: "Заменить на",
  caseSensitive: "Учитывать регистр",
  previewChanges: "Показать изменения",
  apply: "Применить изменения",
  noMatches: "Совпадений нет",
  changes: "Изменяемые блоки",
  referenceImport: "Импортировать референс",
  mappingHint:
    "Выберите главу оригинала, затем соответствующую главу референса. После правок сохраните сопоставления.",
  removeMapping: "Убрать сопоставление",
  noReference:
    "Импортируйте референс: готовые переводы автоматически заполнят непереведённые главы.",
  unmapped: "Не сопоставлено",
  saveMappings: "Сохранить сопоставление",
  format: "Формат",
  unfinished: "Содержимое экспорта",
  translatedOnly: "Переведённые главы",
  translatedOnlyHint: "Главы без сохранённого перевода пропускаются. Обложка и главы только с картинками сохраняются до последней переведённой главы.",
  noTranslatedChapters: "В выбранных главах нет сохранённого перевода или глав только с картинками.",
  reject: "Только полный перевод",
  originals: "Вся книга с оригиналами",
  exportArchive: "Экспорт архива проекта",
  chooseDestination: "Выбрать файл",
  exported: "Экспорт завершён",
  instructionHint:
    "Используются при переводе этой главы. Сохранение пометит её перевод и зависимый контекст для проверки.",
  model: "Модель",
  endpoint: "Адрес провайдера",
  apiKey: "API-ключ",
  keyStored: "API-ключ настроен",
  keyMissing: "API-ключ не задан",
  keyHint: "Оставьте пустым, чтобы сохранить текущий ключ",
  providerHint:
    "Для новых заданий. Запущенные задания сохраняют свои настройки модели.",
  interfaceLanguage: "Язык интерфейса",
  refresh: "Обновить",
  selection: "Область",
  allChapters: "Все главы",
  selectedChapter: "Текущая глава",
  selectChapter: "Выберите главу",
  done: "Готово",
  keyboard: "Ctrl/Cmd+S — сохранить · Ctrl/Cmd+K — команды",
  previewMode: "Предпросмотр интерфейса · пример данных",
  processing: "Обработка",
  queued: "В очереди",
  running: "Выполняется",
  succeeded: "Завершено",
  failed: "Ошибка",
  cancelling: "Отменяется",
  cancelled: "Отменено",
  interrupted: "Прервано",
  resume: "Продолжить",
  book_translation: "Перевод",
  book_metadata: "Сведения о книге",
  book_title: "Перевести заголовок",
  book_retarget: "Исправление терминов",
  retarget: "Исправить в переводах",
  retargetFragments: "Найдено фрагментов",
  retargetHint:
    "Термин сохранён. Исправить подходящие фрагменты в указанном количестве глав, включая саммари? Без подтверждения перевод не меняется.",
  translateTitle: "Перевести заголовок",
  translatedChapterTitle: "Переведённый заголовок главы",
  importScanning: "Читаем файл или папку…",
  importFinalizing: "Завершаем импорт…",
  importCreating: "Открываем книгу…",
  importProgress: "Прогресс импорта",
  importWorking:
    "Приложение работает. Обработка большого файла может потребовать времени.",
  book_glossary: "Извлечение терминов",
};
const zh: Record<Key, string> = {
  narration: "有声书",
  audioEngine: "内存中的模型",
  audioEngineUnloaded: "未加载",
  audioEngineLoading: "正在加载模型…",
  audioEngineReady: "已就绪",
  audioLoad: "加载模型",
  audioUnload: "卸载模型",
  audioEngineHint: "在所选设备上加载一次，即可用于各章节和后续任务。模型会保留在内存中，直到卸载或关闭应用。创建 MP3 时也会按需自动加载。",
  audioPausing: "正在暂停…",
  audioPauseHint: "正在完成当前片段；模型将保留在内存中。",
  audioIntro: "在本机生成有声书。每章保存为 MP3，并附全书播放列表。",
  audioModel: "语音模型",
  audioReady: "已下载",
  audioRuntimeMissing: "此版本缺少语音引擎。请安装包含语音引擎的版本。",
  audioDownload: "下载或继续下载模型",
  audioDownloadFailed: "下载失败。请检查连接后继续。",
  audioVerifying: "正在验证下载文件…",
  audioPause: "暂停",
  audioResume: "继续已保存文本",
  audioOptions: "朗读内容",
  audioText: "文本",
  audioTranslation: "译文",
  audioOriginal: "原文",
  audioRange: "章节范围",
  audioFrom: "起始章节",
  audioTo: "结束章节",
  audioVoice: "声音",
  audioDevice: "计算设备",
  audioAuto: "自动（优先 GPU）",
  audioCpuHint: "CPU 生成可能较慢，请先尝试一章。CUDA 需要支持 NVIDIA 的运行时。所有声音均支持俄语，发音有所不同。",
  audioStart: "生成 MP3",
  audioJobs: "语音任务",
  audioEmptyJobs: "请选择章节和声音。朗读译文时，所选章节必须翻译完整。",
  audioRunning: "生成中",
  audioPaused: "已暂停",
  audioInterrupted: "已中断",
  audioFailed: "失败",
  audioFinished: "已完成",
  audioProgress: "朗读进度",
  audioListen: "试听",
  audioPreviewRefresh: "最新片段",
  audioPreviewSave: "将片段保存为 MP3",
  audioPreviewSaved: "片段已保存为 MP3。",
  audioPreviewHint: "试听最新已保存音频的最多 30 秒。朗读进行中或暂停时均可使用。",
  audioPreviewWaiting: "第一个片段完成后即可试听，无需等待整章。",
  audioPreviewUnavailable: "暂无已保存音频。请等待第一个片段完成或继续朗读。",
  audioPlaybackError: "无法播放片段。请重新加载最新片段。",
  audioPreparing: "正在准备语音模型…",
  audioSave: "保存 MP3 章节",
  audioSaved: "已保存 MP3 章节和播放列表。",
  audioOpenFolder: "打开文件夹",
  audioBusy: "另一朗读任务正在运行，请先暂停。",
  audioModels: "请先下载所有语音模型文件。",
  audioLanguage: "Qwen3-TTS 不支持该语言。",
  audioIncomplete: "所选章节缺少译文或译名。请完成翻译或选择原文。",
  audioEmpty: "所选章节没有文本。",
  audioCuda: "NVIDIA CUDA 不可用。请选择 CPU 或安装 CUDA 运行时。",
  audioMemory: "内存不足。请关闭其他应用或尝试 CPU。",
  audioWorker: "语音引擎已停止。可从保存的进度继续。",
  audioStorage: "无法读写音频。请检查磁盘空间和文件夹权限。",
  audioOutput: "模型返回了无效音频。请继续以重试该片段。",
  audioTooLong: "片段达到生成上限，音频未保存。请继续重试。",
  audioVersion: "此语音任务版本不受支持。请新建任务。",
  audioNotFinished: "请等待朗读完成后再导出。",

  previousPage: "上一页",
  nextPage: "下一页",
  openBook: "打开书籍",
  chooseBook: "选择书籍",
  importBookSettings: "翻译设置",
  volumeTitle: "卷名",
  volumeTitleWorking: "处理中…",
  chapterEditBusy: "正在处理本章或下一章，暂时无法编辑本章。",
  deleteChapter: "删除章节",
  deleteChapterConfirm: "从项目中删除“{title}”？章节原文、已保存译文和参考映射将被删除，且无法撤销。原始书籍文件保留。",
  chapterDeleteBusy: "删除章节前请停止项目中正在运行的任务。",
  chapterDeleted: "此章节已删除。请为剩余章节启动新任务。",
  metadataLanguageError: "模型返回的书籍信息语言不正确。请重试。",
  glossaryOutputError: "术语提取失败：模型返回了无效术语或不完整的响应。请重试任务。",
  providerTransportError: "无法连接翻译服务。请检查网络和超时设置。",
  providerHttpError: "翻译服务拒绝了请求。",
  providerResponseError: "翻译服务返回了无效响应。",
  translationOutputError: "模型未返回所有必需的翻译片段。请重试任务。",
  glossaryFinishError: "术语响应被中断或超出了输出令牌限制。",
  glossaryJsonError: "术语响应不符合所需的 JSON 格式。",

  unsupported: "不支持此项目格式。请从源文件创建新项目。",
  commands: "命令",
  library: "项目",
  importArchive: "导入项目",
  settings: "设置",
  book: "书籍",
  close: "关闭",
  cancel: "取消",
  save: "保存",
  retry: "重试",
  reload: "放弃本地修改并重新加载",
  delete: "删除项目",
  deleteConfirm: "删除项目及其结果？原始文件将保留。",
  welcome: "每份译作都有自己的工作空间",
  welcomeHint: "选择书籍和翻译语言，随后并排处理原文与译文。",
  emptyProjects: "暂无项目",
  open: "打开",
  assistantApplied: "更改已应用，无需再次确认。",
  assistantConflict: "章节或设置已更改，此建议已过期。请让助手重新准备修改，已应用的更改会保留。",
  diagnostics: "诊断",
  fullLogging: "完整诊断日志",
  fullLoggingHint: "立即生效，记录处理步骤、组件检查和命令耗时，不记录 API 密钥、书籍正文或图片。重现问题后保存日志。",
  exportDiagnostics: "保存诊断日志",
  loading: "加载中…",
  exporting: "正在导出…",
  error: "操作未能完成。",
  noKey: "请在设置中添加 API 密钥以开始处理。",
  conflict:
    "内容已在别处更改。本地修改仍保留在编辑器中，可重新加载已保存的版本。",
  exists: "同名文件已存在。请选择其他名称。",
  incomplete: "部分章节未翻译或需要检查。请完成翻译，或选择包含原文。",
  chooseSource: "选择源文件",
  sourceFile: "源文件",
  name: "书名",
  sourceLanguage: "原文语言",
  targetLanguage: "译文语言",
  defaultTargetLanguage: "默认译文语言",
  defaultTargetLanguageHint: "用于创建新项目。",
  fixedLanguages: "语言选定后不能更改。",
  metadataAfterCreate: "导入后翻译书名和作者并生成简介（AI）",
  choose: "请选择…",
  preview: "导入预览",
  bookFormats: "TXT、EPUB、FB2、PDF 或 ZIP",
  importWarning: "创建项目之前请检查源文件。",
  chapters: "章节",
  discardConfirm: "放弃未保存的更改并重新加载已保存的译文？",
  jobChapter: "章节",
  jobStages: "步骤",
  jobContext: "更新上下文",
  chapterFilter: "查找章节",
  reader: "正文",
  overview: "概览",
  glossary: "术语表",
  reference: "参考译文",
  chapterStatusFilter: "章节状态",
  chapterFailed: "翻译失败",
  chapterInProgress: "正在翻译",
  chapterDone: "已翻译",
  chapterSkipped: "无可翻译文本",
  chapterPending: "等待翻译",
  languageIssues: "未翻译或外语片段",

  originReference: "来自参考译文",
  originManual: "人工",
  originModel: "模型",
  replace: "查找与替换",
  export: "导出",
  jobs: "任务",
  clearFinishedJobs: "清除已结束的任务",
  noJobs: "暂无处理任务",
  assistantSendHint: "Enter 发送 · Shift+Enter 换行",
  translationOptions: "翻译选项",
  translationProgress: "翻译进度",
  remainingTime: "预计剩余",
  estimatingTime: "正在估算时间…",
  etaHours: "小时",
  etaMinutes: "分钟",
  etaSeconds: "秒",
  translateChapter: "翻译章节",
  translatePage: "翻译",
  translateBatch: "翻译本批次",
  bookTitle: "书名",
  assistant: "AI 助手",
  assistantHint:
    "上下文包含当前章节、全书说明和最多 100 个术语。建议在 30 分钟后或应用重启后失效。",
  you: "你",
  actionResult: "操作结果",
  before: "修改前",
  after: "修改后",
  decline: "拒绝",
  assistantMessage: "消息",
  assistantExample: "检查本章中的人名并建议术语表修改。",
  assistantAutoRun: "自动应用本次请求的建议操作",
  send: "发送",

  cover: "封面",
  chooseCover: "选择封面",
  removeCover: "移除封面",
  useGenerated: "使用生成值",
  bookPrompt: "全书翻译说明",
  bookPromptHint:
    "应用于下一批次。已有译文将保留供检查。修改说明前请停止当前批次。",

  automaticGlossary: "每章翻译完成后自动更新术语表。",
  referenceGlossaryHint: "导入参考译文或更改章节映射后，会自动更新对应章节的术语表。",
  batchCount: "每批章节数",
  chooseFolder: "选择图片文件夹",
  providerProfiles: "模型配置",
  projectProviders: "项目模型",
  defaultProvider: "默认提供商",
  regionEditHint:
    "拖动区域移动，拖动角落调整大小。应用后从原图重建清理和文字，保留当前译文。修改后的矩形将全部清除。",
  applyRegions: "应用",

  noProviderProfiles:
    "尚无配置。填写名称、API 模型、地址和密钥并保存，然后在下方选择。",
  missingProfile: "配置不可用",
  newProfile: "新建配置",
  profileName: "配置名称",
  bookSearch: "搜索书籍",
  searchText: "查找文本",
  moreResults: "更多结果",

  saveProfile: "保存配置",
  applyRoles: "保存项目模型",
  bookTranslationProfile: "书籍翻译",
  assistantProfile: "AI 助手",
  profileKeyHint: "更改服务地址会清除旧密钥，除非输入新密钥。",
  temperature: "温度",
  contextTokens: "上下文窗口（令牌）",
  outputTokens: "最大输出令牌数",
  fileMenu: "文件",
  helpMenu: "帮助",
  about: "关于",
  version: "版本",
  build: "构建",
  builtAt: "构建日期",
  distributionNotice: "免费开源软件 · MIT 许可证。",
  replaceMode: "替换",
  replaceTranslationOnly: "在译文中替换",
  noEligibleChapters: "所选范围内没有待翻译的文本章节。",
  batchHint: "本批次完成后停止。开始下一批前请检查译文和术语表。",
  force: "替换现有译文",
  instructions: "章节指令",
  original: "原文",
  translation: "译文",
  noTranslation: "翻译此章节后即可编辑。",
  noChapter: "请选择章节",
  saving: "保存中…",
  saved: "已保存",
  unsaved: "存在未保存的修改",
  review: "需要检查",
  current: "当前版本",
  metadata: "书籍信息",
  generateSummary: "AI 生成简介",
  generateMetadata: "翻译书名和作者",
  noMetadata: "尚未生成书籍信息。",
  staleMetadata: "信息基于旧版本生成。",
  source: "来源",
  author: "作者",
  summary: "简介",
  extractTerms: "提取术语",
  extractionBatchHint:
    "处理下一批符合条件的章节。除非启用重复提取，否则跳过已处理的章节。",
  repeatExtraction: "重新提取已处理章节",
  newTerm: "添加术语",
  glossarySearch: "搜索原文或译文术语（区分大小写）",
  pinnedOnly: "仅固定术语",
  totalTerms: "术语总数",
  termsFound: "找到术语",
  noMatchingTerms: "没有符合筛选条件的术语。",
  termSource: "原文术语",
  termTarget: "译文",
  termKind: "类型",
  glossarySearchShort: "搜索术语…",
  kindPerson: "人物",
  kindLocation: "地点",
  kindOrganization: "组织",
  kindTerm: "术语",
  pinned: "固定",
  occurrences: "出现次数",
  more: "加载更多",
  remove: "删除",
  emptyTerms: "暂无术语。可以手动添加或从书中提取。",
  find: "查找",
  replacement: "替换为",
  caseSensitive: "区分大小写",
  previewChanges: "预览修改",
  apply: "应用修改",
  noMatches: "没有匹配项",
  changes: "修改的文本块",
  referenceImport: "导入参考译文",
  mappingHint: "选择原文章节，再选择对应的参考章节。完成后保存对应关系。",
  removeMapping: "移除对应关系",
  noReference: "导入参考译文并手动对应章节。",
  unmapped: "未对应",
  saveMappings: "保存对应关系",
  format: "格式",
  unfinished: "导出内容",
  translatedOnly: "已翻译章节和插图",
  translatedOnlyHint: "跳过没有完整译文的章节，保留封面及最后一个已翻译章节之前的纯图片章节。",
  noTranslatedChapters: "所选章节中没有可用的译文或纯图片章节。",
  reject: "仅允许完整译文",
  originals: "全书（未翻译章节使用原文）",
  exportArchive: "导出项目归档",
  chooseDestination: "选择目标文件",
  exported: "导出完成",
  instructionHint: "翻译该章节时使用。保存后现有译文和相关上下文将需要检查。",
  model: "模型",
  endpoint: "服务地址",
  apiKey: "API 密钥",
  keyStored: "已配置 API 密钥",
  keyMissing: "未配置 API 密钥",
  keyHint: "留空以保留当前密钥",
  providerHint: "适用于新任务。正在运行的任务保留原有模型设置。",
  interfaceLanguage: "界面语言",
  refresh: "刷新",
  selection: "范围",
  allChapters: "全部章节",
  selectedChapter: "当前章节",
  selectChapter: "选择章节",
  done: "完成",
  keyboard: "Ctrl/Cmd+S 保存 · Ctrl/Cmd+K 打开命令",
  previewMode: "界面预览 · 示例数据",
  processing: "处理中",
  queued: "排队中",
  running: "运行中",
  succeeded: "已完成",
  failed: "失败",
  cancelling: "正在取消",
  cancelled: "已取消",
  interrupted: "已中断",
  resume: "继续",
  book_translation: "翻译",
  book_metadata: "书籍信息",
  book_title: "翻译标题",
  book_retarget: "修正术语",
  retarget: "修正已有译文",
  retargetFragments: "匹配片段",
  retargetHint:
    "术语已保存。是否修正指定数量章节及摘要中的相关片段？确认前不会修改译文。",
  translateTitle: "翻译标题",
  translatedChapterTitle: "翻译后的章节标题",
  importScanning: "正在读取文件或文件夹…",
  importFinalizing: "正在完成导入…",
  importCreating: "正在打开书籍…",
  importProgress: "导入进度",
  importWorking: "应用正在处理，大型文件可能需要一些时间。",
  book_glossary: "提取术语",
};
export type T = (key: Key) => string;
export const translator =
  (lang: Lang): T =>
  (key) =>
    ({ en, ru, zh })[lang][key];
export function errorText(error: unknown, t: T): string {
  const e = error as {
    code?: string;
    messageKey?: string;
    params?: {
      field?: string;
      status?: string;
      reason?: string;
      finishReason?: string;
    };
  } | null;
  if (e?.messageKey === "errors.audio") {
    const key = e.params?.reason === "audioRuntime" ? "audioRuntimeMissing" : e.params?.reason;
    return key && key in en ? t(key as Key) : t("audioWorker");
  }
  if (e?.params?.field === "chapterEditBusy") return t("chapterEditBusy");
  if (e?.params?.field === "chapterDeleteBusy") return t("chapterDeleteBusy");
  if (e?.params?.field === "chapterDeleted") return t("chapterDeleted");
  if (e?.params?.field === "metadataLanguage") return t("metadataLanguageError");
  if (e?.messageKey === "errors.glossaryOutput") {
    const reasons: Record<string, Key> = {
      finish: "glossaryFinishError", json: "glossaryJsonError",
    };
    const reason = reasons[e.params?.reason ?? ""];
    return t(reason ?? "glossaryOutputError") + (e.params?.finishReason ? ` (${e.params.finishReason})` : "");
  }
  if (e?.messageKey === "errors.providerHttp") return `${t("providerHttpError")}${e.params?.status ? ` HTTP ${e.params.status}` : ""}`;
  if (e?.messageKey === "errors.providerTransport") return t("providerTransportError");
  if (["errors.providerResponse", "errors.providerChoices", "errors.providerResponseSize"].includes(e?.messageKey ?? "")) return t("providerResponseError");
  if (e?.messageKey === "errors.translationSegments") return t("translationOutputError");
  if (e?.code === "unsupported_version") return t("unsupported");
  if (e?.code === "revision_conflict") return t("conflict");
  if (e?.messageKey === "errors.apiKeyRequired") return t("noKey");
  if (e?.params?.field === "noEligibleChapters") return t("noEligibleChapters");
  if (e?.params?.field === "destinationExists") return t("exists");
  if (e?.params?.field === "noTranslatedChapters") return t("noTranslatedChapters");
  if (e?.params?.field === "incompleteTranslation") return t("incomplete");
  return error instanceof Error
    ? error.message
    : typeof error === "string"
      ? error
      : e?.messageKey
        ? `${t("error")} (${e.messageKey}${e.params?.field ? `: ${e.params.field}` : ""})`
        : t("error");
}
export const languages = [
  "en",
  "ru",
  "zh",
  "ja",
  "ko",
  "de",
  "fr",
  "es",
  "it",
  "pt",
];
export const languageName = (code: string, lang: Lang) => {
  try {
    return new Intl.DisplayNames([lang], { type: "language" }).of(code) ?? code;
  } catch {
    return code;
  }
};
