import type { Lang } from "../i18n";
const en = {
  metadataLanguageError: "The model returned book details in the wrong language. Please retry.",
  glossaryOutputError: "Glossary extraction failed: the model returned invalid terms or an incomplete response. Retry the job.",
  providerTransportError: "Could not reach the translation provider. Check the connection and provider timeout.",
  providerHttpError: "The translation provider rejected the request.",
  providerResponseError: "The translation provider returned an invalid response.",
  translationOutputError: "The model did not return all required translation segments. Retry the job.",
  glossaryFinishError: "The glossary response was interrupted or exceeded the output token limit.",
  glossaryJsonError: "The glossary response does not match the required JSON format.",

  mangaModels: "Manga models",
  modelDownloadHint:
    "Weights are downloaded from Hugging Face only when requested and cached locally. Closing this dialog keeps the download running. After an app restart, resume it here.",
  modelExperimental:
    "Experimental processing model. Downloading does not enable manga processing: runtime compatibility and image quality still need validation.",
  modelMissing: "Not downloaded",
  modelDownloading: "Downloading",
  modelVerifying: "Verifying file",
  modelPaused: "Download paused",
  modelDownloaded: "Downloaded and verified",
  modelDownload: "Download from Hugging Face",
  modelPause: "Pause download",
  modelRemove: "Remove local files",
  modelUnknown: "This model is not in the catalog.",
  modelBusy: "Another download is in progress.",
  modelNetwork: "Download interrupted. Check your connection and resume.",
  modelSizeError:
    "The server returned an unexpected file size or range. Download was not installed.",
  modelHashError: "File verification failed. Download it again.",
  modelStorageError:
    "Cannot access the model cache. Check free disk space and file permissions.",

  unsupported:
    "This project uses an unsupported format. Create a new project from its source.",
  commands: "Commands",
  library: "Projects",
  newProject: "New project",
  importArchive: "Import project",
  settings: "Settings",
  book: "Book",
  manga: "Manga",
  close: "Close",
  cancel: "Cancel",
  save: "Save",
  retry: "Retry",
  reload: "Discard local edits and reload",
  delete: "Delete project",
  deleteConfirm:
    "Delete this project and its results? Source files will be kept.",
  welcome: "A workspace for every translation",
  welcomeHint:
    "Create a book or manga project. Choose its languages once, then work with the original and translation side by side.",
  emptyProjects: "No projects yet",
  open: "Open",
  loading: "Loading…",
  exporting: "Exporting…",
  error: "The operation could not be completed.",
  noKey: "Add an API key in Settings to start processing.",
  conflict:
    "This content changed elsewhere. Your local edits are kept. Reload to use the saved version.",
  exists: "A file with this name already exists. Choose another name.",
  incomplete:
    "Some chapters need translation or review. Complete them, or choose originals for unfinished chapters.",
  chooseKind: "What are you translating?",
  chooseSource: "Choose source",
  sourceFile: "Source file",
  name: "Project name",
  sourceLanguage: "Original language",
  targetLanguage: "Translation language",
  defaultTargetLanguage: "Default translation language",
  defaultTargetLanguageHint: "Used when creating new projects.",
  fixedLanguages: "These languages are fixed for this project.",
  create: "Create project",
  metadataAfterCreate:
    "Translate title and author and create an annotation after import (AI)",
  choose: "Choose…",
  preview: "Import preview",
  bookFormats: "TXT, EPUB, FB2, PDF or ZIP",
  mangaFormats: "CBZ or ZIP with page images",
  importWarning: "Check the source preview before creating the project.",
  chapters: "Chapters",
  discardConfirm: "Discard unsaved changes and reload the saved translation?",
  jobChapter: "Chapter",
  jobStages: "Stages",
  jobContext: "Updating context",
  chapterFilter: "Find a chapter",
  reader: "Text",
  overview: "Overview",
  glossary: "Glossary",
  reference: "Reference",
  chapterStatusFilter: "Chapter status",
  chapterFailed: "Translation failed",
  chapterInProgress: "Translating",
  chapterDone: "Translated",
  chapterSkipped: "No text to translate",
  chapterPending: "Awaiting translation",
  languageIssues: "Untranslated or foreign-language fragments",

  originReference: "From reference",
  originManual: "Manual",
  originModel: "Model",
  replace: "Find and replace",
  export: "Export",
  jobs: "Jobs",
  noJobs: "No processing jobs",
  assistantSendHint: "Enter to send · Shift+Enter for a new line",
  translationOptions: "Translation options",
  translationProgress: "Translation progress",
  remainingTime: "Approx. remaining",
  estimatingTime: "Estimating time…",
  etaHours: "h",
  etaMinutes: "min",
  etaSeconds: "s",
  translateChapter: "Translate chapter",
  batchTranslation: "Batch translation",
  translatePage: "Translate",
  translateBatch: "Translate batch",
  bookTitle: "Book title",
  assistant: "AI assistant",
  assistantHint:
    "Current chapter, book instructions and up to 100 glossary terms. Proposals expire after 30 minutes or an app restart.",
  you: "You",
  actionResult: "Action result",
  before: "Before",
  after: "After",
  decline: "Reject",
  assistantMessage: "Message",
  assistantExample:
    "Check the names in this chapter and suggest glossary corrections.",
  assistantAutoRun: "Automatically apply actions proposed for this request",
  send: "Send",

  cover: "Cover",
  chooseCover: "Choose cover",
  removeCover: "Remove cover",
  useGenerated: "Use generated value",
  bookPrompt: "Book translation instructions",
  bookPromptHint:
    "Applied to the next batch. Earlier translations remain available for review. Stop an active batch before changing its instructions.",

  batchCount: "Chapters per batch",
  batchGlossary: "Extract terms before translating the batch",
  chooseFolder: "Choose image folder",
  providerProfiles: "Model profiles",
  projectProviders: "Project models",
  defaultProvider: "Default provider",
  regionEditHint:
    "Drag regions to move them; drag the corner to resize. Apply rebuilds cleanup and text from the original, using the current translations. Edited rectangles are erased in full.",
  mangaPageBusy:
    "Wait for the current job to finish or cancel it before applying edits.",
  mangaRebuildingPage: "Applying region changes…",
  manga_rebuild: "Rebuild page",
  applyRegions: "Apply",
  textDirection: "Text direction",
  horizontalText: "Horizontal",
  verticalText: "Vertical (90°)",
  mangaTextOverflow:
    "Text does not fit in a region. Enlarge the region or change its text direction, then apply.",
  mangaFontCoverage:
    "The rendering font does not support some translated characters.",
  mangaWorkerTimeout: "Page processing timed out.",
  mangaLocalProcessing:
    "Local image processing failed. Try rebuilding the page; check the manga runtime if it fails again.",

  noProviderProfiles:
    "No profiles yet. Enter a name, API model, endpoint and key, then save the profile. It will appear in the selectors below.",
  mangaProfileSetupHint:
    "By default, recognition uses DeepSeek Flash with your shared API key; translation uses your shared model settings. No separate profile is required. Recognition requires an API model that accepts images. Translation uses a text model. You can select the same profile for both if it supports both tasks. Apply the selected profiles below.",
  missingProfile: "Profile unavailable",
  newProfile: "New profile",
  profileName: "Profile name",
  bookSearch: "Search book",
  searchText: "Text to find",
  moreResults: "More results",

  saveProfile: "Save profile",
  applyRoles: "Save project models",
  bookTranslationProfile: "Book translation",
  assistantProfile: "AI assistant",
  mangaRecognitionProfile: "Manga recognition",
  mangaTranslationProfile: "Manga translation",
  profileKeyHint:
    "Changing the endpoint clears the old key unless you enter a replacement.",
  temperature: "Temperature",
  outputTokens: "Maximum output tokens",

  zoom: "Zoom",
  volumes: "Volumes",
  allVolumes: "All volumes",
  regions: "Regions",
  region: "Region",
  notRecognized: "This page has not been recognized yet.",
  noRecognizedText: "Recognition found no readable text.",
  recognitionStale: "Recognition is outdated. Review before using it.",
  translationNotReady: "Translation is not ready yet.",
  manualRegionText: "Contains manually edited text",
  fileMenu: "File",
  helpMenu: "Help",
  about: "About",
  version: "Version",
  build: "Build",
  builtAt: "Built at",
  distributionNotice: "Free and open-source software · MIT License.",
  imageFiles: "Images",
  mangaExportUnavailable: "Page export is not available yet.",
  replaceMode: "Replace",
  replaceTranslationOnly: "Replace in translated text",
  wholePage: "Whole page",
  fitPage: "Fit width",
  previousPage: "Previous page",
  nextPage: "Next page",
  noEligibleChapters: "No untranslated text chapters in this selection.",
  batchHint:
    "Stops after this batch. Review translations and glossary before starting the next one.",
  force: "Replace existing translations",
  instructions: "Chapter instructions",
  original: "Original",
  translation: "Translation",
  noTranslation: "Translate this chapter to start editing.",
  noChapter: "Choose a chapter",
  saving: "Saving…",
  saved: "Saved",
  unsaved: "Unsaved changes",
  review: "Needs review",
  current: "Current",
  metadata: "Book details",
  generateSummary: "Generate annotation with AI",
  generateMetadata: "Translate title and author",
  noMetadata: "No generated details yet.",
  staleMetadata: "Details were generated from an earlier version.",
  source: "Source",
  author: "Author",
  summary: "Summary",
  extractTerms: "Extract terms",
  extractionBatchHint:
    "Process the next eligible chapters. Previously processed chapters are skipped unless repeated extraction is enabled.",
  repeatExtraction: "Extract previously processed chapters again",
  newTerm: "Add term",
  glossarySearch: "Find a source or translated term (case-sensitive)",
  pinnedOnly: "Pinned only",
  totalTerms: "Total terms",
  termsFound: "Terms found",
  noMatchingTerms: "No terms match these filters.",
  termSource: "Original term",
  termTarget: "Translation",
  termKind: "Type",
  glossarySearchShort: "Search terms…",
  kindPerson: "Person",
  kindLocation: "Location",
  kindOrganization: "Organization",
  kindTerm: "Term",
  pinned: "Pinned",
  occurrences: "Occurrences",
  more: "Load more",
  remove: "Delete",
  emptyTerms: "No terms yet. Add a term or extract them from the book.",
  find: "Find",
  replacement: "Replace with",
  caseSensitive: "Match case",
  previewChanges: "Preview changes",
  apply: "Apply changes",
  noMatches: "No matches",
  changes: "Changed blocks",
  referenceImport: "Import reference",
  mappingHint:
    "Select an original chapter, then its reference chapter. Save the mappings when finished.",
  removeMapping: "Remove mapping",
  noReference:
    "Import a reference translation to fill untranslated chapters automatically.",
  unmapped: "Not mapped",
  saveMappings: "Save chapter mapping",
  format: "Format",
  unfinished: "Export content",
  translatedOnly: "Translated chapters",
  translatedOnlyHint: "Chapters without a saved translation are skipped. The cover and image-only chapters up to the last translated chapter are preserved.",
  noTranslatedChapters: "No saved translations or image-only chapters in this selection.",
  reject: "Require complete translations",
  originals: "Whole book with untranslated originals",
  exportArchive: "Export project archive",
  chooseDestination: "Choose destination",
  exported: "Export complete",
  instructionHint:
    "Used when this chapter is translated. Saving invalidates its existing translation and dependent context.",
  model: "Model",
  endpoint: "Provider URL",
  apiKey: "API key",
  keyStored: "An API key is configured",
  keyMissing: "No API key configured",
  keyHint: "Leave empty to keep the current key",
  providerHint:
    "Applies to new jobs. Running jobs retain their saved model settings.",
  interfaceLanguage: "Interface language",
  pages: "Pages",
  mangaPreflight: "Manga processing setup",
  mangaPreflightHint:
    "Local configuration check only. No page uploads or model downloads. Provider access and recognition quality still require verification.",
  mangaConfigured: "Configured locally",
  mangaCapabilityUnavailable: "This processing stage is not available yet.",
  mangaDetection: "Text regions",
  mangaRecognition: "Text recognition",
  mangaTranslation: "Dialogue translation",
  mangaMasks: "Text masks",
  mangaInpainting: "Image cleanup",
  mangaLettering: "Lettering",
  mangaRecognitionProfileRequired:
    "Select a manga recognition profile in Settings → Model profiles.",
  mangaTranslationProfileRequired:
    "Select a manga translation profile in Settings → Model profiles.",
  mangaProfileKeyRequired:
    "Add the API key for this profile in Settings → Model profiles.",
  mangaProfileInvalid:
    "Check the selected profile and provider address in Settings → Model profiles.",
  mangaTranslationUnavailable:
    "The region translation stage is not implemented yet.",
  mangaMasksUnavailable:
    "Automatic text-pixel segmentation is not implemented yet.",
  mangaInpaintingUnavailable:
    "The cleanup runtime is not connected yet. Downloading LaMa alone does not enable this stage.",
  mangaLetteringUnavailable:
    "Text layout and overflow checking are not implemented yet.",

  page: "Page",
  noPages: "No pages",
  mangaUnavailable:
    "Automatic manga processing requires configured recognition, cleanup and lettering models. Page viewing is available.",
  refresh: "Refresh",
  selection: "Scope",
  allChapters: "All chapters",
  selectedChapter: "Current chapter",
  selectChapter: "Select a chapter",
  done: "Done",
  keyboard: "Ctrl/Cmd+S saves · Ctrl/Cmd+K opens commands",
  previewMode: "Interface preview · sample data",
  processing: "Processing",
  queued: "Queued",
  running: "Running",
  succeeded: "Completed",
  failed: "Failed",
  cancelling: "Cancelling",
  cancelled: "Cancelled",
  interrupted: "Interrupted",
  resume: "Resume",
  book_translation: "Translation",
  book_metadata: "Book details",
  book_title: "Translate title",
  book_retarget: "Correct glossary terms",
  retarget: "Correct in translations",
  retargetFragments: "Matching fragments",
  retargetHint:
    "The term is saved. Correct matching fragments in this many chapters, including summaries? Nothing runs until you confirm.",
  translateTitle: "Translate title",
  translatedChapterTitle: "Translated chapter title",
  manga_recognition: "Manga recognition",
  manga_translation: "Manga translation",
  manga_masks: "Text masks",
  manga_inpainting: "Manga cleanup",
  manga_lettering: "Manga lettering",
  manga_automatic: "Manga translation",
  mangaCheckingSetup: "Checking translation setup…",
  mangaSetupRequired: "To start translation",
  mangaCountRequired: "Enter at least one page.",
  importScanning: "Reading file or folder…",
  importPages: "Importing pages and generating thumbnails…",
  importFinalizing: "Finishing import…",
  importCreating: "Creating project…",
  importProgress: "Import progress",
  importWorking: "The application is working. Large files may take a while.",
  mangaBatchHint: "From the current page; completed pages are skipped.",
  mangaRuntimeMissing:
    "Manga runtime is missing or damaged. Reinstall the application.",
  mangaMaskModelRequired: "Download the text-mask model in Settings → Models.",
  mangaCleanupModelRequired: "Download the cleanup model in Settings → Models.",
  book_glossary: "Term extraction",
};
type Key = keyof typeof en;
const ru: Record<Key, string> = {
  metadataLanguageError: "Модель вернула описание книги не на языке перевода. Повторите задание.",
  glossaryOutputError: "Не удалось извлечь глоссарий: модель вернула некорректные термины или неполный ответ. Повторите задание.",
  providerTransportError: "Не удалось связаться с провайдером перевода. Проверьте соединение и тайм-аут провайдера.",
  providerHttpError: "Провайдер перевода отклонил запрос.",
  providerResponseError: "Провайдер перевода вернул некорректный ответ.",
  translationOutputError: "Модель не вернула все необходимые фрагменты перевода. Повторите задание.",
  glossaryFinishError: "Ответ с глоссарием прерван или превысил лимит выходных токенов.",
  glossaryJsonError: "Ответ с глоссарием не соответствует требуемому формату JSON.",

  mangaModels: "Модели для манги",
  modelDownloadHint:
    "Веса скачиваются с Hugging Face только по запросу и хранятся локально. Закрытие этого окна не прерывает загрузку. После перезапуска приложения продолжите её здесь.",
  modelExperimental:
    "Экспериментальная модель обработки. Скачивание пока не включает обработку манги: ещё предстоит проверить совместимость и качество результата.",
  modelMissing: "Не скачана",
  modelDownloading: "Скачивание",
  modelVerifying: "Проверка файла",
  modelPaused: "Загрузка приостановлена",
  modelDownloaded: "Скачана и проверена",
  modelDownload: "Скачать с Hugging Face",
  modelPause: "Приостановить",
  modelRemove: "Удалить локальные файлы",
  modelUnknown: "Модели нет в каталоге.",
  modelBusy: "Другая загрузка уже выполняется.",
  modelNetwork:
    "Загрузка прервана. Проверьте соединение и продолжите скачивание.",
  modelSizeError:
    "Сервер вернул неожиданный размер или диапазон файла. Модель не установлена.",
  modelHashError: "Файл не прошёл проверку. Скачайте его повторно.",
  modelStorageError:
    "Не удалось открыть кеш моделей. Проверьте свободное место и права доступа.",

  unsupported:
    "Этот формат проекта не поддерживается. Создайте новый проект из исходного файла.",
  commands: "Команды",
  library: "Проекты",
  newProject: "Новый проект",
  importArchive: "Импорт проекта",
  settings: "Настройки",
  book: "Книга",
  manga: "Манга",
  close: "Закрыть",
  cancel: "Отмена",
  save: "Сохранить",
  retry: "Повторить",
  reload: "Отбросить локальные правки и загрузить заново",
  delete: "Удалить проект",
  deleteConfirm: "Удалить проект и его результаты? Исходные файлы сохранятся.",
  welcome: "Рабочее пространство для каждого перевода",
  welcomeHint:
    "Создайте проект книги или манги. Выберите языки один раз, затем работайте с оригиналом и переводом рядом.",
  emptyProjects: "Пока нет проектов",
  open: "Открыть",
  loading: "Загрузка…",
  exporting: "Выгрузка…",
  error: "Не удалось выполнить операцию.",
  noKey: "Добавьте API-ключ в настройках, чтобы начать обработку.",
  conflict:
    "Содержимое изменилось в другом месте. Локальные правки сохранены в редакторе. Загрузите сохранённую версию заново.",
  exists: "Файл с таким именем уже существует. Выберите другое имя.",
  incomplete:
    "Некоторые главы не переведены или требуют проверки. Завершите их либо включите оригиналы непереведённых глав.",
  chooseKind: "Что вы переводите?",
  chooseSource: "Выбрать исходник",
  sourceFile: "Исходный файл",
  name: "Название проекта",
  sourceLanguage: "Язык оригинала",
  targetLanguage: "Язык перевода",
  defaultTargetLanguage: "Язык перевода по умолчанию",
  defaultTargetLanguageHint: "Подставляется при создании новых проектов.",
  fixedLanguages: "Эти языки закреплены за проектом и не меняются.",
  create: "Создать проект",
  metadataAfterCreate:
    "Перевести название и автора, создать аннотацию после импорта (ИИ)",
  choose: "Выберите…",
  preview: "Предпросмотр импорта",
  bookFormats: "TXT, EPUB, FB2, PDF или ZIP",
  mangaFormats: "CBZ или ZIP с изображениями страниц",
  importWarning: "Проверьте исходник перед созданием проекта.",
  chapters: "Главы",
  discardConfirm:
    "Отменить несохранённые изменения и загрузить сохранённый перевод?",
  jobChapter: "Глава",
  jobStages: "Этапы",
  jobContext: "Обновление контекста",
  chapterFilter: "Найти главу",
  reader: "Текст",
  overview: "Обзор",
  glossary: "Глоссарий",
  reference: "Референс",
  chapterStatusFilter: "Статус глав",
  chapterFailed: "Ошибка перевода",
  chapterInProgress: "Переводится",
  chapterDone: "Переведено",
  chapterSkipped: "Нет текста для перевода",
  chapterPending: "Ожидает перевода",
  languageIssues: "Непереведённые или иноязычные фрагменты",

  originReference: "Из референса",
  originManual: "Вручную",
  originModel: "Модель",
  replace: "Поиск и замена",
  export: "Экспорт",
  jobs: "Задания",
  noJobs: "Нет заданий обработки",
  assistantSendHint: "Enter — отправить · Shift+Enter — новая строка",
  translationOptions: "Параметры перевода",
  translationProgress: "Прогресс перевода",
  remainingTime: "Примерно осталось",
  estimatingTime: "Оцениваем время…",
  etaHours: "ч",
  etaMinutes: "мин",
  etaSeconds: "с",
  translateChapter: "Перевести главу",
  batchTranslation: "Перевод партиями",
  translatePage: "Перевести",
  translateBatch: "Перевести партию",
  bookTitle: "Название книги",
  assistant: "ИИ-ассистент",
  assistantHint:
    "Контекст: текущая глава, общий промпт и до 100 терминов словаря. Предложения действуют 30 минут и до перезапуска приложения.",
  you: "Вы",
  actionResult: "Результат действия",
  before: "До",
  after: "После",
  decline: "Отклонить",
  assistantMessage: "Сообщение",
  assistantExample:
    "Проверь имена в этой главе и предложи исправления словаря.",
  assistantAutoRun:
    "Автоматически применять предложенные действия для этого запроса",
  send: "Отправить",

  cover: "Обложка",
  chooseCover: "Выбрать обложку",
  removeCover: "Удалить обложку",
  useGenerated: "Использовать сгенерированное",
  bookPrompt: "Общий промпт книги",
  bookPromptHint:
    "Применяется к следующей партии. Предыдущие переводы сохраняются для проверки. Перед изменением инструкций остановите текущую партию.",

  batchCount: "Глав в партии",
  batchGlossary: "Пополнять словарь перед переводом",
  chooseFolder: "Выбрать папку изображений",
  providerProfiles: "Профили моделей",
  projectProviders: "Модели проекта",
  defaultProvider: "Провайдер по умолчанию",
  regionEditHint:
    "Перемещайте рамки и тяните за угол. «Применить» очистит исправленные области целиком и заново наложит перевод.",
  mangaPageBusy:
    "Дождитесь завершения текущего задания или отмените его перед применением правок.",
  mangaRebuildingPage: "Применяем изменения областей…",
  manga_rebuild: "Пересборка страницы",
  applyRegions: "Применить",
  textDirection: "Направление текста",
  horizontalText: "Горизонтально",
  verticalText: "Вертикально (90°)",
  mangaTextOverflow:
    "Текст не помещается в регион. Увеличьте рамку или измените направление текста и нажмите «Применить».",
  mangaFontCoverage: "Шрифт не поддерживает некоторые символы перевода.",
  mangaWorkerTimeout: "Превышено время обработки страницы.",
  mangaLocalProcessing:
    "Ошибка локальной обработки изображения. Попробуйте пересобрать страницу; при повторной ошибке проверьте компонент обработки манги.",

  noProviderProfiles:
    "Профилей пока нет. Укажите название, модель API, адрес и ключ, затем сохраните профиль. Он появится в списках ниже.",
  mangaProfileSetupHint:
    "По умолчанию распознавание использует DeepSeek Flash с общим API-ключом, перевод — модель из общих настроек. Отдельный профиль создавать не нужно. Для распознавания нужна модель API с поддержкой изображений, для перевода — текстовая. Можно выбрать один профиль для обеих задач, если модель поддерживает их. Примените выбранные профили ниже.",
  missingProfile: "Профиль недоступен",
  newProfile: "Новый профиль",
  profileName: "Название профиля",
  bookSearch: "Поиск по книге",
  searchText: "Найти текст",
  moreResults: "Ещё результаты",

  saveProfile: "Сохранить профиль",
  applyRoles: "Сохранить модели проекта",
  bookTranslationProfile: "Перевод книги",
  assistantProfile: "ИИ-ассистент",
  mangaRecognitionProfile: "Распознавание манги",
  mangaTranslationProfile: "Перевод манги",
  profileKeyHint:
    "При смене адреса старый ключ удаляется, если не указан новый.",
  temperature: "Температура",
  outputTokens: "Максимум токенов ответа",

  zoom: "Масштаб",
  volumes: "Тома",
  allVolumes: "Все тома",
  regions: "Области",
  region: "Область",
  notRecognized: "Страница ещё не распознана.",
  noRecognizedText: "Распознавание не обнаружило читаемого текста.",
  recognitionStale:
    "Результат распознавания устарел. Проверьте его перед использованием.",
  translationNotReady: "Перевод ещё не готов.",
  manualRegionText: "Есть ручные правки текста",
  fileMenu: "Файл",
  helpMenu: "Справка",
  about: "О программе",
  version: "Версия",
  build: "Сборка",
  builtAt: "Дата сборки",
  distributionNotice: "Свободное ПО с открытым исходным кодом · Лицензия MIT.",
  imageFiles: "Изображения",
  mangaExportUnavailable: "Экспорт страниц пока недоступен.",
  replaceMode: "Замена",
  replaceTranslationOnly: "Замена в тексте перевода",
  wholePage: "Страница целиком",
  fitPage: "По ширине",
  previousPage: "Предыдущая страница",
  nextPage: "Следующая страница",
  noEligibleChapters: "В выбранной области нет непереведённых текстовых глав.",
  batchHint:
    "После партии перевод остановится. Проверьте перевод и словарь перед следующим запуском.",
  force: "Заменить существующий перевод",
  instructions: "Инструкции главы",
  original: "Оригинал",
  translation: "Перевод",
  noTranslation: "Переведите главу, чтобы начать редактирование.",
  noChapter: "Выберите главу",
  saving: "Сохранение…",
  saved: "Сохранено",
  unsaved: "Есть несохранённые правки",
  review: "Требует проверки",
  current: "Актуально",
  metadata: "О книге",
  generateSummary: "Сгенерировать аннотацию ИИ",
  generateMetadata: "Перевести название и автора",
  noMetadata: "Сведения ещё не сгенерированы.",
  staleMetadata: "Сведения созданы по предыдущей версии.",
  source: "Исходник",
  author: "Автор",
  summary: "Аннотация",
  extractTerms: "Извлечь термины",
  extractionBatchHint:
    "Обработать следующие подходящие главы. Уже обработанные пропускаются, если не включено повторное извлечение.",
  repeatExtraction: "Повторно извлечь из обработанных глав",
  newTerm: "Добавить термин",
  glossarySearch: "Поиск по оригиналу или переводу термина (с учётом регистра)",
  pinnedOnly: "Только закреплённые",
  totalTerms: "Всего терминов",
  termsFound: "Найдено терминов",
  noMatchingTerms: "По заданным условиям термины не найдены.",
  termSource: "Термин в оригинале",
  termTarget: "Перевод",
  termKind: "Тип",
  glossarySearchShort: "Поиск по словарю…",
  kindPerson: "Персонаж",
  kindLocation: "Место",
  kindOrganization: "Организация",
  kindTerm: "Термин",
  pinned: "Закреплён",
  occurrences: "Вхождения",
  more: "Загрузить ещё",
  remove: "Удалить",
  emptyTerms: "Терминов пока нет. Добавьте термин или извлеките их из книги.",
  find: "Найти",
  replacement: "Заменить на",
  caseSensitive: "Учитывать регистр",
  previewChanges: "Показать изменения",
  apply: "Применить изменения",
  noMatches: "Совпадений нет",
  changes: "Изменяемые блоки",
  referenceImport: "Импортировать референс",
  mappingHint:
    "Выберите главу оригинала, затем соответствующую главу референса. После правок сохраните сопоставления.",
  removeMapping: "Убрать сопоставление",
  noReference:
    "Импортируйте референс: готовые переводы автоматически заполнят непереведённые главы.",
  unmapped: "Не сопоставлено",
  saveMappings: "Сохранить сопоставление",
  format: "Формат",
  unfinished: "Содержимое экспорта",
  translatedOnly: "Переведённые главы",
  translatedOnlyHint: "Главы без сохранённого перевода пропускаются. Обложка и главы только с картинками сохраняются до последней переведённой главы.",
  noTranslatedChapters: "В выбранных главах нет сохранённого перевода или глав только с картинками.",
  reject: "Только полный перевод",
  originals: "Вся книга с оригиналами",
  exportArchive: "Экспорт архива проекта",
  chooseDestination: "Выбрать файл",
  exported: "Экспорт завершён",
  instructionHint:
    "Используются при переводе этой главы. Сохранение пометит её перевод и зависимый контекст для проверки.",
  model: "Модель",
  endpoint: "Адрес провайдера",
  apiKey: "API-ключ",
  keyStored: "API-ключ настроен",
  keyMissing: "API-ключ не задан",
  keyHint: "Оставьте пустым, чтобы сохранить текущий ключ",
  providerHint:
    "Для новых заданий. Запущенные задания сохраняют свои настройки модели.",
  interfaceLanguage: "Язык интерфейса",
  pages: "Страницы",
  mangaPreflight: "Готовность обработки манги",
  mangaPreflightHint:
    "Проверяются только локальные настройки, без отправки страниц и скачивания моделей. Доступ к провайдеру и качество распознавания ещё требуют проверки.",
  mangaConfigured: "Настроено локально",
  mangaCapabilityUnavailable: "Этот этап обработки пока недоступен.",
  mangaDetection: "Области текста",
  mangaRecognition: "Распознавание",
  mangaTranslation: "Перевод реплик",
  mangaMasks: "Маски текста",
  mangaInpainting: "Очистка изображения",
  mangaLettering: "Размещение перевода",
  mangaRecognitionProfileRequired:
    "Выберите профиль распознавания манги: Настройки → Профили моделей.",
  mangaTranslationProfileRequired:
    "Выберите профиль перевода манги: Настройки → Профили моделей.",
  mangaProfileKeyRequired:
    "Добавьте API-ключ профиля: Настройки → Профили моделей.",
  mangaProfileInvalid:
    "Проверьте выбранный профиль и адрес провайдера: Настройки → Профили моделей.",
  mangaTranslationUnavailable: "Перевод реплик по областям пока не реализован.",
  mangaMasksUnavailable:
    "Автоматическое выделение пикселей текста пока не реализовано.",
  mangaInpaintingUnavailable:
    "Обработчик очистки ещё не подключён. Одного скачивания LaMa недостаточно.",
  mangaLetteringUnavailable:
    "Размещение текста и проверка переполнения пока не реализованы.",

  page: "Страница",
  noPages: "Нет страниц",
  mangaUnavailable:
    "Для автоматической обработки манги нужны настроенные модели распознавания, очистки и набора текста. Просмотр страниц доступен.",
  refresh: "Обновить",
  selection: "Область",
  allChapters: "Все главы",
  selectedChapter: "Текущая глава",
  selectChapter: "Выберите главу",
  done: "Готово",
  keyboard: "Ctrl/Cmd+S — сохранить · Ctrl/Cmd+K — команды",
  previewMode: "Предпросмотр интерфейса · пример данных",
  processing: "Обработка",
  queued: "В очереди",
  running: "Выполняется",
  succeeded: "Завершено",
  failed: "Ошибка",
  cancelling: "Отменяется",
  cancelled: "Отменено",
  interrupted: "Прервано",
  resume: "Продолжить",
  book_translation: "Перевод",
  book_metadata: "Сведения о книге",
  book_title: "Перевести заголовок",
  book_retarget: "Исправление терминов",
  retarget: "Исправить в переводах",
  retargetFragments: "Найдено фрагментов",
  retargetHint:
    "Термин сохранён. Исправить подходящие фрагменты в указанном количестве глав, включая саммари? Без подтверждения перевод не меняется.",
  translateTitle: "Перевести заголовок",
  translatedChapterTitle: "Переведённый заголовок главы",
  manga_recognition: "Распознавание манги",
  manga_translation: "Перевод манги",
  manga_masks: "Маски текста",
  manga_inpainting: "Очистка манги",
  manga_lettering: "Нанесение перевода манги",
  manga_automatic: "Перевод манги",
  mangaCheckingSetup: "Проверяем готовность перевода…",
  mangaSetupRequired: "Чтобы начать перевод",
  mangaCountRequired: "Укажите хотя бы одну страницу.",
  importScanning: "Читаем файл или папку…",
  importPages: "Импортируем страницы и создаём миниатюры…",
  importFinalizing: "Завершаем импорт…",
  importCreating: "Создаём проект…",
  importProgress: "Прогресс импорта",
  importWorking:
    "Приложение работает. Обработка большого файла может потребовать времени.",
  mangaBatchHint: "С текущей страницы; готовые страницы пропускаются.",
  mangaRuntimeMissing:
    "Компонент обработки манги отсутствует или повреждён. Переустановите приложение.",
  mangaMaskModelRequired: "Скачайте модель маски текста в Настройки → Модели.",
  mangaCleanupModelRequired: "Скачайте модель очистки в Настройки → Модели.",
  book_glossary: "Извлечение терминов",
};
const zh: Record<Key, string> = {
  metadataLanguageError: "模型返回的书籍信息语言不正确。请重试。",
  glossaryOutputError: "术语提取失败：模型返回了无效术语或不完整的响应。请重试任务。",
  providerTransportError: "无法连接翻译服务。请检查网络和超时设置。",
  providerHttpError: "翻译服务拒绝了请求。",
  providerResponseError: "翻译服务返回了无效响应。",
  translationOutputError: "模型未返回所有必需的翻译片段。请重试任务。",
  glossaryFinishError: "术语响应被中断或超出了输出令牌限制。",
  glossaryJsonError: "术语响应不符合所需的 JSON 格式。",

  mangaModels: "漫画模型",
  modelDownloadHint:
    "仅按需从 Hugging Face 下载权重并缓存到本地。关闭此窗口不会中断下载；重启应用后可在此继续。",
  modelExperimental:
    "实验性处理模型。下载不代表漫画处理已可用；仍需验证运行时兼容性和图像质量。",
  modelMissing: "未下载",
  modelDownloading: "下载中",
  modelVerifying: "正在校验",
  modelPaused: "下载已暂停",
  modelDownloaded: "已下载并校验",
  modelDownload: "从 Hugging Face 下载",
  modelPause: "暂停下载",
  modelRemove: "删除本地文件",
  modelUnknown: "目录中没有此模型。",
  modelBusy: "另一个下载正在进行。",
  modelNetwork: "下载已中断。请检查连接后继续。",
  modelSizeError: "服务器返回了意外的文件大小或范围。模型未安装。",
  modelHashError: "文件校验失败，请重新下载。",
  modelStorageError: "无法访问模型缓存。请检查磁盘空间和文件权限。",

  unsupported: "不支持此项目格式。请从源文件创建新项目。",
  commands: "命令",
  library: "项目",
  newProject: "新建项目",
  importArchive: "导入项目",
  settings: "设置",
  book: "书籍",
  manga: "漫画",
  close: "关闭",
  cancel: "取消",
  save: "保存",
  retry: "重试",
  reload: "放弃本地修改并重新加载",
  delete: "删除项目",
  deleteConfirm: "删除项目及其结果？原始文件将保留。",
  welcome: "每份译作都有自己的工作空间",
  welcomeHint: "创建书籍或漫画项目。一次选定语言，随后并排处理原文与译文。",
  emptyProjects: "暂无项目",
  open: "打开",
  loading: "加载中…",
  exporting: "正在导出…",
  error: "操作未能完成。",
  noKey: "请在设置中添加 API 密钥以开始处理。",
  conflict:
    "内容已在别处更改。本地修改仍保留在编辑器中，可重新加载已保存的版本。",
  exists: "同名文件已存在。请选择其他名称。",
  incomplete: "部分章节未翻译或需要检查。请完成翻译，或选择包含原文。",
  chooseKind: "要翻译什么？",
  chooseSource: "选择源文件",
  sourceFile: "源文件",
  name: "项目名称",
  sourceLanguage: "原文语言",
  targetLanguage: "译文语言",
  defaultTargetLanguage: "默认译文语言",
  defaultTargetLanguageHint: "用于创建新项目。",
  fixedLanguages: "语言选定后不能更改。",
  create: "创建项目",
  metadataAfterCreate: "导入后翻译书名和作者并生成简介（AI）",
  choose: "请选择…",
  preview: "导入预览",
  bookFormats: "TXT、EPUB、FB2、PDF 或 ZIP",
  mangaFormats: "包含页面图片的 CBZ 或 ZIP",
  importWarning: "创建项目之前请检查源文件。",
  chapters: "章节",
  discardConfirm: "放弃未保存的更改并重新加载已保存的译文？",
  jobChapter: "章节",
  jobStages: "步骤",
  jobContext: "更新上下文",
  chapterFilter: "查找章节",
  reader: "正文",
  overview: "概览",
  glossary: "术语表",
  reference: "参考译文",
  chapterStatusFilter: "章节状态",
  chapterFailed: "翻译失败",
  chapterInProgress: "正在翻译",
  chapterDone: "已翻译",
  chapterSkipped: "无可翻译文本",
  chapterPending: "等待翻译",
  languageIssues: "未翻译或外语片段",

  originReference: "来自参考译文",
  originManual: "人工",
  originModel: "模型",
  replace: "查找与替换",
  export: "导出",
  jobs: "任务",
  noJobs: "暂无处理任务",
  assistantSendHint: "Enter 发送 · Shift+Enter 换行",
  translationOptions: "翻译选项",
  translationProgress: "翻译进度",
  remainingTime: "预计剩余",
  estimatingTime: "正在估算时间…",
  etaHours: "小时",
  etaMinutes: "分钟",
  etaSeconds: "秒",
  translateChapter: "翻译章节",
  batchTranslation: "批量翻译",
  translatePage: "翻译",
  translateBatch: "翻译本批次",
  bookTitle: "书名",
  assistant: "AI 助手",
  assistantHint:
    "上下文包含当前章节、全书说明和最多 100 个术语。建议在 30 分钟后或应用重启后失效。",
  you: "你",
  actionResult: "操作结果",
  before: "修改前",
  after: "修改后",
  decline: "拒绝",
  assistantMessage: "消息",
  assistantExample: "检查本章中的人名并建议术语表修改。",
  assistantAutoRun: "自动应用本次请求的建议操作",
  send: "发送",

  cover: "封面",
  chooseCover: "选择封面",
  removeCover: "移除封面",
  useGenerated: "使用生成值",
  bookPrompt: "全书翻译说明",
  bookPromptHint:
    "应用于下一批次。已有译文将保留供检查。修改说明前请停止当前批次。",

  batchCount: "每批章节数",
  batchGlossary: "翻译本批次前提取术语",
  chooseFolder: "选择图片文件夹",
  providerProfiles: "模型配置",
  projectProviders: "项目模型",
  defaultProvider: "默认提供商",
  regionEditHint:
    "拖动区域移动，拖动角落调整大小。应用后从原图重建清理和文字，保留当前译文。修改后的矩形将全部清除。",
  mangaPageBusy: "请等待当前任务完成或取消后再应用更改。",
  mangaRebuildingPage: "正在应用区域更改…",
  manga_rebuild: "重建页面",
  applyRegions: "应用",
  textDirection: "文字方向",
  horizontalText: "横向",
  verticalText: "纵向（90°）",
  mangaTextOverflow: "文字超出区域。请扩大区域或更改文字方向后应用。",
  mangaFontCoverage: "字体不支持部分译文字符。",
  mangaWorkerTimeout: "页面处理超时。",
  mangaLocalProcessing:
    "本地图像处理失败。请重建页面，如再次失败请检查漫画处理组件。",

  noProviderProfiles:
    "尚无配置。填写名称、API 模型、地址和密钥并保存，然后在下方选择。",
  mangaProfileSetupHint:
    "默认使用通用 API 设置，无需创建单独配置。识别需要支持图像的 API 模型，翻译使用文本模型。如果模型支持两项任务，可以使用同一配置。请在下方应用所选配置。",
  missingProfile: "配置不可用",
  newProfile: "新建配置",
  profileName: "配置名称",
  bookSearch: "搜索书籍",
  searchText: "查找文本",
  moreResults: "更多结果",

  saveProfile: "保存配置",
  applyRoles: "保存项目模型",
  bookTranslationProfile: "书籍翻译",
  assistantProfile: "AI 助手",
  mangaRecognitionProfile: "漫画识别",
  mangaTranslationProfile: "漫画翻译",
  profileKeyHint: "更改服务地址会清除旧密钥，除非输入新密钥。",
  temperature: "温度",
  outputTokens: "最大输出令牌数",

  zoom: "缩放",
  volumes: "卷",
  allVolumes: "所有卷",
  regions: "文本区域",
  region: "区域",
  notRecognized: "此页尚未识别。",
  noRecognizedText: "未识别到可读文本。",
  recognitionStale: "识别结果已过期，请在使用前检查。",
  translationNotReady: "翻译尚未完成。",
  manualRegionText: "包含手动修改的文本",
  fileMenu: "文件",
  helpMenu: "帮助",
  about: "关于",
  version: "版本",
  build: "构建",
  builtAt: "构建日期",
  distributionNotice: "免费开源软件 · MIT 许可证。",
  imageFiles: "图片",
  mangaExportUnavailable: "页面导出尚不可用。",
  replaceMode: "替换",
  replaceTranslationOnly: "在译文中替换",
  wholePage: "整页",
  fitPage: "适合宽度",
  previousPage: "上一页",
  nextPage: "下一页",
  noEligibleChapters: "所选范围内没有待翻译的文本章节。",
  batchHint: "本批次完成后停止。开始下一批前请检查译文和术语表。",
  force: "替换现有译文",
  instructions: "章节指令",
  original: "原文",
  translation: "译文",
  noTranslation: "翻译此章节后即可编辑。",
  noChapter: "请选择章节",
  saving: "保存中…",
  saved: "已保存",
  unsaved: "存在未保存的修改",
  review: "需要检查",
  current: "当前版本",
  metadata: "书籍信息",
  generateSummary: "AI 生成简介",
  generateMetadata: "翻译书名和作者",
  noMetadata: "尚未生成书籍信息。",
  staleMetadata: "信息基于旧版本生成。",
  source: "来源",
  author: "作者",
  summary: "简介",
  extractTerms: "提取术语",
  extractionBatchHint:
    "处理下一批符合条件的章节。除非启用重复提取，否则跳过已处理的章节。",
  repeatExtraction: "重新提取已处理章节",
  newTerm: "添加术语",
  glossarySearch: "搜索原文或译文术语（区分大小写）",
  pinnedOnly: "仅固定术语",
  totalTerms: "术语总数",
  termsFound: "找到术语",
  noMatchingTerms: "没有符合筛选条件的术语。",
  termSource: "原文术语",
  termTarget: "译文",
  termKind: "类型",
  glossarySearchShort: "搜索术语…",
  kindPerson: "人物",
  kindLocation: "地点",
  kindOrganization: "组织",
  kindTerm: "术语",
  pinned: "固定",
  occurrences: "出现次数",
  more: "加载更多",
  remove: "删除",
  emptyTerms: "暂无术语。可以手动添加或从书中提取。",
  find: "查找",
  replacement: "替换为",
  caseSensitive: "区分大小写",
  previewChanges: "预览修改",
  apply: "应用修改",
  noMatches: "没有匹配项",
  changes: "修改的文本块",
  referenceImport: "导入参考译文",
  mappingHint: "选择原文章节，再选择对应的参考章节。完成后保存对应关系。",
  removeMapping: "移除对应关系",
  noReference: "导入参考译文并手动对应章节。",
  unmapped: "未对应",
  saveMappings: "保存对应关系",
  format: "格式",
  unfinished: "导出内容",
  translatedOnly: "已翻译章节和插图",
  translatedOnlyHint: "跳过没有完整译文的章节，保留封面及最后一个已翻译章节之前的纯图片章节。",
  noTranslatedChapters: "所选章节中没有可用的译文或纯图片章节。",
  reject: "仅允许完整译文",
  originals: "全书（未翻译章节使用原文）",
  exportArchive: "导出项目归档",
  chooseDestination: "选择目标文件",
  exported: "导出完成",
  instructionHint: "翻译该章节时使用。保存后现有译文和相关上下文将需要检查。",
  model: "模型",
  endpoint: "服务地址",
  apiKey: "API 密钥",
  keyStored: "已配置 API 密钥",
  keyMissing: "未配置 API 密钥",
  keyHint: "留空以保留当前密钥",
  providerHint: "适用于新任务。正在运行的任务保留原有模型设置。",
  interfaceLanguage: "界面语言",
  pages: "页面",
  mangaPreflight: "漫画处理准备情况",
  mangaPreflightHint:
    "仅检查本地配置，不上传页面或下载模型。提供商访问和识别质量仍需验证。",
  mangaConfigured: "已在本地配置",
  mangaCapabilityUnavailable: "此处理阶段尚不可用。",
  mangaDetection: "文字区域",
  mangaRecognition: "文字识别",
  mangaTranslation: "对白翻译",
  mangaMasks: "文字蒙版",
  mangaInpainting: "图像修复",
  mangaLettering: "译文排版",
  mangaRecognitionProfileRequired: "请在设置 → 模型配置中选择漫画识别配置。",
  mangaTranslationProfileRequired: "请在设置 → 模型配置中选择漫画翻译配置。",
  mangaProfileKeyRequired: "请在设置 → 模型配置中添加此配置的 API 密钥。",
  mangaProfileInvalid: "请在设置 → 模型配置中检查所选配置和提供商地址。",
  mangaTranslationUnavailable: "区域对白翻译尚未实现。",
  mangaMasksUnavailable: "自动文字像素分割尚未实现。",
  mangaInpaintingUnavailable:
    "修复运行时尚未接入。仅下载 LaMa 无法启用此阶段。",
  mangaLetteringUnavailable: "文本排版和溢出检查尚未实现。",

  page: "页",
  noPages: "暂无页面",
  mangaUnavailable:
    "漫画自动处理需要配置识别、清理和排版模型。目前可以浏览页面。",
  refresh: "刷新",
  selection: "范围",
  allChapters: "全部章节",
  selectedChapter: "当前章节",
  selectChapter: "选择章节",
  done: "完成",
  keyboard: "Ctrl/Cmd+S 保存 · Ctrl/Cmd+K 打开命令",
  previewMode: "界面预览 · 示例数据",
  processing: "处理中",
  queued: "排队中",
  running: "运行中",
  succeeded: "已完成",
  failed: "失败",
  cancelling: "正在取消",
  cancelled: "已取消",
  interrupted: "已中断",
  resume: "继续",
  book_translation: "翻译",
  book_metadata: "书籍信息",
  book_title: "翻译标题",
  book_retarget: "修正术语",
  retarget: "修正已有译文",
  retargetFragments: "匹配片段",
  retargetHint:
    "术语已保存。是否修正指定数量章节及摘要中的相关片段？确认前不会修改译文。",
  translateTitle: "翻译标题",
  translatedChapterTitle: "翻译后的章节标题",
  manga_recognition: "漫画识别",
  manga_translation: "漫画翻译",
  manga_masks: "文字蒙版",
  manga_inpainting: "漫画清理",
  manga_lettering: "漫画嵌字",
  manga_automatic: "漫画翻译",
  mangaCheckingSetup: "正在检查翻译设置…",
  mangaSetupRequired: "开始翻译前",
  mangaCountRequired: "请至少输入一页。",
  importScanning: "正在读取文件或文件夹…",
  importPages: "正在导入页面并生成缩略图…",
  importFinalizing: "正在完成导入…",
  importCreating: "正在创建项目…",
  importProgress: "导入进度",
  importWorking: "应用正在处理，大型文件可能需要一些时间。",
  mangaBatchHint: "从当前页开始，跳过已完成的页面。",
  mangaRuntimeMissing: "漫画运行组件缺失或损坏，请重新安装应用。",
  mangaMaskModelRequired: "请在设置 → 模型中下载文字蒙版模型。",
  mangaCleanupModelRequired: "请在设置 → 模型中下载清理模型。",
  book_glossary: "提取术语",
};
export type T = (key: Key) => string;
export const translator =
  (lang: Lang): T =>
  (key) =>
    ({ en, ru, zh })[lang][key];
export function errorText(error: unknown, t: T): string {
  const e = error as {
    code?: string;
    messageKey?: string;
    params?: {
      field?: string;
      status?: string;
      reason?: string;
      finishReason?: string;
    };
  } | null;
  if (e?.params?.field === "metadataLanguage") return t("metadataLanguageError");
  if (e?.messageKey === "errors.glossaryOutput") {
    const reasons: Record<string, Key> = {
      finish: "glossaryFinishError", json: "glossaryJsonError",
    };
    const reason = reasons[e.params?.reason ?? ""];
    return t(reason ?? "glossaryOutputError") + (e.params?.finishReason ? ` (${e.params.finishReason})` : "");
  }
  if (e?.messageKey === "errors.providerHttp") return `${t("providerHttpError")}${e.params?.status ? ` HTTP ${e.params.status}` : ""}`;
  if (e?.messageKey === "errors.providerTransport") return t("providerTransportError");
  if (["errors.providerResponse", "errors.providerChoices", "errors.providerResponseSize"].includes(e?.messageKey ?? "")) return t("providerResponseError");
  if (e?.messageKey === "errors.translationSegments") return t("translationOutputError");
  if (e?.code === "unsupported_version") return t("unsupported");
  if (e?.code === "revision_conflict") return t("conflict");
  if (e?.messageKey === "errors.apiKeyRequired") return t("noKey");
  if (e?.params?.field === "noEligibleChapters") return t("noEligibleChapters");
  if (e?.params?.field === "destinationExists") return t("exists");
  if (e?.params?.field === "noTranslatedChapters") return t("noTranslatedChapters");
  if (e?.params?.field === "incompleteTranslation") return t("incomplete");
  if (
    [
      "mangaTextOverflow",
      "mangaFontCoverage",
      "mangaWorkerTimeout",
      "mangaLocalProcessing",
    ].includes(e?.params?.field ?? "")
  )
    return t(e!.params!.field as Parameters<T>[0]);
  return error instanceof Error
    ? error.message
    : typeof error === "string"
      ? error
      : e?.messageKey
        ? `${t("error")} (${e.messageKey}${e.params?.field ? `: ${e.params.field}` : ""})`
        : t("error");
}
export const languages = [
  "en",
  "ru",
  "zh",
  "ja",
  "ko",
  "de",
  "fr",
  "es",
  "it",
  "pt",
];
export const languageName = (code: string, lang: Lang) => {
  try {
    return new Intl.DisplayNames([lang], { type: "language" }).of(code) ?? code;
  } catch {
    return code;
  }
};
