//! Per-project session state and project filesystem layout.

use std::collections::HashMap;
use std::path::Path;
use std::sync::atomic::AtomicBool;
use std::sync::{Arc, Mutex};

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::export::fb2::Cover;
use crate::paths::app_data_dir;
use crate::reference::Reference;

/// Per-project session state.
#[derive(Default)]
pub struct Session {
    pub(crate) db_path: Option<String>,
    pub(crate) source_path: Option<String>,
    pub(crate) title: Option<String>,
    pub(crate) author: Option<String>,
    pub(crate) reference: Option<Reference>,
    pub(crate) style: Option<String>,
    pub(crate) cancel: Option<Arc<AtomicBool>>,
    pub(crate) running: bool,
    /// Source or reference was a `.zip` → default to a zipped output.
    pub(crate) zipped_input: bool,
    /// Translated book title shown in the UI and written to output.
    pub(crate) title_translated: Option<String>,
    /// Translated / transliterated author, so a Chinese name is not rendered as
    /// boxes in the Latin/Cyrillic-only PDF font.
    pub(crate) author_translated: Option<String>,
    /// Annotation / summary (auto from a source FB2, or edited by the user).
    pub(crate) summary: Option<String>,
    /// Cover image (auto from a source FB2, or replaced by the user).
    pub(crate) cover: Option<Cover>,
}

/// Managed app state: one `Session` per open project, keyed by project id, so
/// projects are isolated and can translate in parallel.
pub struct AppState(Mutex<HashMap<String, Session>>);

impl AppState {
    pub fn new() -> Self {
        AppState(Mutex::new(HashMap::new()))
    }

    /// Run `f` with the session for `id`, creating an empty one if absent.
    pub(crate) fn with<R>(&self, id: &str, f: impl FnOnce(&mut Session) -> R) -> R {
        let mut map = self.0.lock().unwrap_or_else(|poisoned| poisoned.into_inner());
        f(map.entry(id.to_string()).or_default())
    }

    /// Remove one project's runtime session without exposing the whole map.
    pub(crate) fn remove(&self, id: &str) -> Option<Session> {
        self.0
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .remove(id)
    }
}

#[derive(Debug, Error, PartialEq, Eq)]
#[error("invalid_project_id")]
pub(crate) struct InvalidProjectId;

/// Validate the identifier before it becomes part of a filesystem path.
///
/// Project ids are generated by the frontend, so they are untrusted IPC input.
/// Restricting them to one filename component prevents `..` / slash traversal
/// in open, delete, import and export commands.
pub(crate) fn validate_project_id(id: &str) -> Result<(), InvalidProjectId> {
    let valid = !id.is_empty()
        && id.len() <= 128
        && id
            .bytes()
            .all(|c| c.is_ascii_alphanumeric() || c == b'-' || c == b'_');
    valid.then_some(()).ok_or(InvalidProjectId)
}

/// A project's own data directory (`<app_data>/projects/<id>/`).
pub(crate) fn project_dir(id: &str) -> Result<std::path::PathBuf, InvalidProjectId> {
    validate_project_id(id)?;
    Ok(app_data_dir().join("projects").join(id))
}

/// The resumable progress DB for a project. Kept in the app data directory (not
/// next to the book) so the source can live on a read-only mount without breaking.
pub(crate) fn db_path_for_project(id: &str) -> anyhow::Result<String> {
    let dir = project_dir(id)?;
    std::fs::create_dir_all(&dir)?;
    Ok(dir.join("progress.db").to_string_lossy().into_owned())
}

/// Remove legacy flat `*.progress.db` files from before the per-project layout.
pub fn cleanup_legacy_data() {
    if let Ok(entries) = std::fs::read_dir(app_data_dir()) {
        for e in entries.flatten() {
            if e.file_name().to_string_lossy().ends_with(".progress.db") {
                let _ = std::fs::remove_file(e.path());
            }
        }
    }
}

/// Project manifest, stored as `project.json` and bundled into an archive so a
/// project is self-describing.
#[derive(Serialize, Deserialize, Default)]
pub(crate) struct Manifest {
    pub(crate) name: String,
    pub(crate) source_path: String,
    pub(crate) ref_path: Option<String>,
}

/// Whether output should default to a zip: "zip in, zip out".
///
/// True when either input the project was built from was zipped, the reference
/// included. That matters here because a project can have a plain-text source
/// and a zipped reference, which is the common shape when a professional
/// translation is downloaded as an archive.
///
/// Derived from the manifest rather than remembered in the session, because the
/// session is rebuilt on every open and used to get this only as a side effect
/// of re-parsing the reference on each activation.
pub(crate) fn zipped_input_for(source_path: Option<&str>, ref_path: Option<&str>) -> bool {
    let is_zip = |p: &str| crate::book::source::is_zip(Path::new(p));
    source_path.is_some_and(is_zip) || ref_path.is_some_and(is_zip)
}

/// The reference file recorded in a project's manifest, if one was attached.
pub(crate) fn manifest_ref_path(id: &str) -> anyhow::Result<Option<String>> {
    let bytes = std::fs::read(project_dir(id)?.join("project.json"))?;
    Ok(serde_json::from_slice::<Manifest>(&bytes)?.ref_path)
}

pub(crate) fn write_manifest(
    id: &str,
    source_path: &str,
    ref_path: Option<&str>,
) -> anyhow::Result<()> {
    let dir = project_dir(id)?;
    std::fs::create_dir_all(&dir)?;
    let name = Path::new(source_path)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("book")
        .to_string();
    let m = Manifest {
        name,
        source_path: source_path.to_string(),
        ref_path: ref_path.map(|s| s.to_string()),
    };
    let bytes = serde_json::to_vec_pretty(&m)?;
    std::fs::write(dir.join("project.json"), bytes)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A zipped reference alone is enough: the source is often a plain .txt.
    #[test]
    fn zipped_input_considers_both_inputs() {
        assert!(!zipped_input_for(Some("/books/novel.txt"), None));
        assert!(zipped_input_for(Some("/books/novel.zip"), None));
        assert!(zipped_input_for(Some("/books/novel.txt"), Some("/refs/pro.zip")));
        assert!(!zipped_input_for(Some("/books/novel.txt"), Some("/refs/pro.fb2")));
        assert!(!zipped_input_for(None, None));
    }

    #[test]
    fn project_dir_nests_under_app_data() {
        let p = project_dir("abc-123").unwrap();
        assert_eq!(p.file_name().and_then(|s| s.to_str()), Some("abc-123"));
        assert!(p.to_string_lossy().contains("projects"));
        assert!(p.to_string_lossy().contains("book-converter"));
    }

    #[test]
    fn db_path_for_project_ends_with_progress_db() {
        let id = format!("test-{}", std::process::id());
        let db = db_path_for_project(&id).unwrap();
        assert!(db.ends_with("progress.db"));
        assert!(db.contains(&id));
        // Clean up the empty dir created by the helper.
        let _ = std::fs::remove_dir_all(project_dir(&id).unwrap());
    }

    #[test]
    fn project_id_rejects_path_traversal() {
        for id in ["", "..", "../outside", "nested/project", r"nested\project", "."] {
            assert_eq!(validate_project_id(id), Err(InvalidProjectId), "{id:?}");
            assert!(project_dir(id).is_err(), "{id:?}");
        }
        for id in ["550e8400-e29b-41d4-a716-446655440000", "p-123_abc"] {
            assert!(validate_project_id(id).is_ok(), "{id:?}");
        }
    }
}

